/**
 * jsGlobals.ts
 * JavaScript global functions, objects, and DOM APIs.
 * Split into logical groups — globals, DOM, events, arrays, objects, etc.
 */

// ── Top-level global objects (suggested when typing standalone) ────────────────

export const JS_GLOBAL_OBJECTS = [
    { name: 'document', snippet: 'document', description: 'The HTML document object' },
    { name: 'window', snippet: 'window', description: 'The browser window object' },
    { name: 'console', snippet: 'console', description: 'Browser console object' },
    { name: 'Math', snippet: 'Math', description: 'Math utility object' },
    { name: 'JSON', snippet: 'JSON', description: 'JSON parse/stringify object' },
    { name: 'Date', snippet: 'Date', description: 'Date and time object' },
    { name: 'Array', snippet: 'Array', description: 'Array utility object' },
    { name: 'Object', snippet: 'Object', description: 'Object utility' },
    { name: 'String', snippet: 'String', description: 'String utility' },
    { name: 'Number', snippet: 'Number', description: 'Number utility' },
    { name: 'Boolean', snippet: 'Boolean', description: 'Boolean utility' },
    { name: 'Promise', snippet: 'Promise', description: 'Promise object' },
    { name: 'Error', snippet: 'Error', description: 'Error object' },
    { name: 'RegExp', snippet: 'RegExp', description: 'Regular expression object' },
    { name: 'Map', snippet: 'Map', description: 'Map collection' },
    { name: 'Set', snippet: 'Set', description: 'Set collection' },
    { name: 'WeakMap', snippet: 'WeakMap', description: 'WeakMap collection' },
    { name: 'WeakSet', snippet: 'WeakSet', description: 'WeakSet collection' },
    { name: 'Symbol', snippet: 'Symbol', description: 'Symbol primitive' },
    { name: 'Proxy', snippet: 'Proxy', description: 'Proxy object' },
    { name: 'Reflect', snippet: 'Reflect', description: 'Reflect API' },
    { name: 'Int8Array', snippet: 'Int8Array', description: '8-bit signed integer typed array' },
    { name: 'Uint8Array', snippet: 'Uint8Array', description: '8-bit unsigned integer typed array' },
    { name: 'Int16Array', snippet: 'Int16Array', description: '16-bit signed integer typed array' },
    { name: 'Uint16Array', snippet: 'Uint16Array', description: '16-bit unsigned integer typed array' },
    { name: 'Int32Array', snippet: 'Int32Array', description: '32-bit signed integer typed array' },
    { name: 'Float32Array', snippet: 'Float32Array', description: '32-bit float typed array' },
    { name: 'Float64Array', snippet: 'Float64Array', description: '64-bit float typed array' },
    { name: 'ArrayBuffer', snippet: 'ArrayBuffer', description: 'Raw binary data buffer' },
    { name: 'localStorage', snippet: 'localStorage', description: 'Local storage object' },
    { name: 'sessionStorage', snippet: 'sessionStorage', description: 'Session storage object' },
    { name: 'location', snippet: 'location', description: 'Window location object' },
    { name: 'history', snippet: 'history', description: 'Browser history object' },
    { name: 'navigator', snippet: 'navigator', description: 'Browser navigator object' },
    { name: 'screen', snippet: 'screen', description: 'Screen information object' },
    { name: 'performance', snippet: 'performance', description: 'Performance timing object' },
    { name: 'crypto', snippet: 'crypto', description: 'Web Crypto API' },
    { name: 'URL', snippet: 'URL', description: 'URL parsing object' },
    { name: 'URLSearchParams', snippet: 'URLSearchParams', description: 'URL query parameter utility' },
    { name: 'FormData', snippet: 'FormData', description: 'Form data object' },
    { name: 'Headers', snippet: 'Headers', description: 'HTTP Headers object' },
    { name: 'Request', snippet: 'Request', description: 'Fetch Request object' },
    { name: 'Response', snippet: 'Response', description: 'Fetch Response object' },
    { name: 'AbortController', snippet: 'AbortController', description: 'Abort fetch/async operations' },
    { name: 'MutationObserver', snippet: 'MutationObserver', description: 'Observe DOM mutations' },
    { name: 'IntersectionObserver', snippet: 'IntersectionObserver', description: 'Observe element visibility' },
    { name: 'ResizeObserver', snippet: 'ResizeObserver', description: 'Observe element size changes' },
    { name: 'event', snippet: 'event', description: 'Current event object' },
    { name: 'undefined', snippet: 'undefined', description: 'Undefined value' },
    { name: 'null', snippet: 'null', description: 'Null value' },
    { name: 'true', snippet: 'true', description: 'Boolean true' },
    { name: 'false', snippet: 'false', description: 'Boolean false' },
    { name: 'Infinity', snippet: 'Infinity', description: 'Infinity value' },
    { name: 'NaN', snippet: 'NaN', description: 'Not a number value' },
    { name: 'this', snippet: 'this', description: 'Current context object' },
    { name: 'arguments', snippet: 'arguments', description: 'Function arguments object' },
    { name: 'globalThis', snippet: 'globalThis', description: 'Global this object' },
];

// ── Console ────────────────────────────────────────────────────────────────────

export const CONSOLE_METHODS = [
    { name: 'log', snippet: 'log($0)', description: 'Log to console' },
    { name: 'error', snippet: 'error($0)', description: 'Log error to console' },
    { name: 'warn', snippet: 'warn($0)', description: 'Log warning to console' },
    { name: 'info', snippet: 'info($0)', description: 'Log info to console' },
    { name: 'debug', snippet: 'debug($0)', description: 'Log debug message' },
    { name: 'table', snippet: 'table($0)', description: 'Log data as table' },
    { name: 'dir', snippet: 'dir($0)', description: 'Log object properties' },
    { name: 'dirxml', snippet: 'dirxml($0)', description: 'Log DOM element as XML' },
    { name: 'group', snippet: "group('$0')", description: 'Start console group' },
    { name: 'groupCollapsed', snippet: "groupCollapsed('$0')", description: 'Start collapsed console group' },
    { name: 'groupEnd', snippet: 'groupEnd()', description: 'End console group' },
    { name: 'time', snippet: "time('$0')", description: 'Start timer' },
    { name: 'timeEnd', snippet: "timeEnd('$0')", description: 'End timer' },
    { name: 'timeLog', snippet: "timeLog('$0')", description: 'Log current timer value' },
    { name: 'timeStamp', snippet: "timeStamp('$0')", description: 'Add timestamp to devtools' },
    { name: 'clear', snippet: 'clear()', description: 'Clear console' },
    { name: 'count', snippet: "count('$0')", description: 'Count calls with label' },
    { name: 'countReset', snippet: "countReset('$0')", description: 'Reset counter' },
    { name: 'assert', snippet: "assert(${1:condition}, '$0')", description: 'Assert condition' },
    { name: 'trace', snippet: 'trace($0)', description: 'Print stack trace' },
    { name: 'profile', snippet: "profile('$0')", description: 'Start CPU profiling' },
    { name: 'profileEnd', snippet: "profileEnd('$0')", description: 'End CPU profiling' },
];

// ── Document methods ───────────────────────────────────────────────────────────

export const DOCUMENT_METHODS = [
    // Querying
    { name: 'getElementById', snippet: "getElementById('$0')", description: 'Get element by ID' },
    { name: 'getElementsByClassName', snippet: "getElementsByClassName('$0')", description: 'Get elements by class name' },
    { name: 'getElementsByTagName', snippet: "getElementsByTagName('$0')", description: 'Get elements by tag name' },
    { name: 'getElementsByName', snippet: "getElementsByName('$0')", description: 'Get elements by name attribute' },
    { name: 'querySelector', snippet: "querySelector('$0')", description: 'Get first matching element' },
    { name: 'querySelectorAll', snippet: "querySelectorAll('$0')", description: 'Get all matching elements' },
    // Creation
    { name: 'createElement', snippet: "createElement('$0')", description: 'Create a new element' },
    { name: 'createElementNS', snippet: "createElementNS('${1:http://www.w3.org/2000/svg}', '${2:svg}')", description: 'Create element with namespace (e.g. SVG)' },
    { name: 'createTextNode', snippet: "createTextNode('$0')", description: 'Create a text node' },
    { name: 'createComment', snippet: "createComment('$0')", description: 'Create a comment node' },
    { name: 'createDocumentFragment', snippet: 'createDocumentFragment()', description: 'Create a document fragment' },
    { name: 'createRange', snippet: 'createRange()', description: 'Create a Range object' },
    { name: 'createEvent', snippet: "createEvent('${1:Event}')", description: 'Create a legacy DOM event' },
    // Events
    { name: 'addEventListener', snippet: "addEventListener('${1:DOMContentLoaded}', () => {\n\t$0\n})", description: 'Add event listener to document' },
    { name: 'removeEventListener', snippet: "removeEventListener('${1:event}', ${2:handler})", description: 'Remove event listener' },
    { name: 'dispatchEvent', snippet: 'dispatchEvent(new Event(\'${1:event}\'))', description: 'Dispatch a DOM event' },
    // Document stream
    { name: 'write', snippet: "write('$0')", description: 'Write to document' },
    { name: 'writeln', snippet: "writeln('$0')", description: 'Write line to document' },
    { name: 'open', snippet: 'open()', description: 'Open document stream' },
    { name: 'close', snippet: 'close()', description: 'Close document stream' },
    // Document info / properties
    { name: 'cookie', snippet: 'cookie', description: 'Document cookies' },
    { name: 'title', snippet: 'title', description: 'Document title' },
    { name: 'URL', snippet: 'URL', description: 'Document URL' },
    { name: 'documentURI', snippet: 'documentURI', description: 'Full document URI' },
    { name: 'domain', snippet: 'domain', description: 'Document domain' },
    { name: 'referrer', snippet: 'referrer', description: 'Referring document URL' },
    { name: 'characterSet', snippet: 'characterSet', description: 'Document character encoding' },
    { name: 'contentType', snippet: 'contentType', description: 'Document content type' },
    { name: 'lastModified', snippet: 'lastModified', description: 'Last modified date string' },
    { name: 'readyState', snippet: 'readyState', description: 'Document loading state (loading/interactive/complete)' },
    { name: 'compatMode', snippet: 'compatMode', description: 'Document rendering mode' },
    { name: 'designMode', snippet: "designMode = '${1:on}'", description: 'Enable editing of entire document' },
    { name: 'hidden', snippet: 'hidden', description: 'Whether document is hidden (Page Visibility API)' },
    { name: 'visibilityState', snippet: 'visibilityState', description: 'Document visibility state' },
    { name: 'fullscreenElement', snippet: 'fullscreenElement', description: 'Currently fullscreen element' },
    { name: 'fullscreenEnabled', snippet: 'fullscreenEnabled', description: 'Whether fullscreen is available' },
    { name: 'pointerLockElement', snippet: 'pointerLockElement', description: 'Currently pointer-locked element' },
    // Element shortcuts
    { name: 'body', snippet: 'body', description: 'Document body element' },
    { name: 'head', snippet: 'head', description: 'Document head element' },
    { name: 'documentElement', snippet: 'documentElement', description: 'Root html element' },
    { name: 'activeElement', snippet: 'activeElement', description: 'Currently focused element' },
    { name: 'scrollingElement', snippet: 'scrollingElement', description: 'Scrolling element (html or body)' },
    // Collections
    { name: 'forms', snippet: 'forms', description: 'All form elements' },
    { name: 'images', snippet: 'images', description: 'All image elements' },
    { name: 'links', snippet: 'links', description: 'All anchor/area elements' },
    { name: 'scripts', snippet: 'scripts', description: 'All script elements' },
    { name: 'styleSheets', snippet: 'styleSheets', description: 'All stylesheets' },
    // Selection & clipboard
    { name: 'getSelection', snippet: 'getSelection()', description: 'Get current text selection' },
    { name: 'hasFocus', snippet: 'hasFocus()', description: 'Check if document has focus' },
    { name: 'execCommand', snippet: "execCommand('${1:copy}')", description: 'Execute editing command (deprecated)' },
    { name: 'elementFromPoint', snippet: 'elementFromPoint(${1:x}, ${2:y})', description: 'Get element at point' },
    { name: 'elementsFromPoint', snippet: 'elementsFromPoint(${1:x}, ${2:y})', description: 'Get all elements at point' },
    { name: 'caretRangeFromPoint', snippet: 'caretRangeFromPoint(${1:x}, ${2:y})', description: 'Get caret range at point' },
    { name: 'exitFullscreen', snippet: 'exitFullscreen()', description: 'Exit fullscreen mode' },
    { name: 'exitPointerLock', snippet: 'exitPointerLock()', description: 'Exit pointer lock' },
    { name: 'adoptNode', snippet: 'adoptNode($0)', description: 'Adopt node from another document' },
    { name: 'importNode', snippet: 'importNode(${1:node}, ${2:true})', description: 'Import node from another document' },
    { name: 'normalize', snippet: 'normalize()', description: 'Merge adjacent text nodes' },
];

// ── Element methods (used after querySelector etc.) ────────────────────────────

export const ELEMENT_METHODS = [
    // Events
    { name: 'addEventListener', snippet: "addEventListener('${1:click}', ($2) => {\n\t$0\n})", description: 'Add event listener' },
    { name: 'removeEventListener', snippet: "removeEventListener('${1:click}', ${2:handler})", description: 'Remove event listener' },
    { name: 'dispatchEvent', snippet: "dispatchEvent(new Event('${1:click}'))", description: 'Dispatch a DOM event' },
    // DOM manipulation
    { name: 'appendChild', snippet: 'appendChild($0)', description: 'Append child element' },
    { name: 'prepend', snippet: 'prepend($0)', description: 'Insert at start of element' },
    { name: 'append', snippet: 'append($0)', description: 'Insert at end of element (accepts strings too)' },
    { name: 'before', snippet: 'before($0)', description: 'Insert before this element' },
    { name: 'after', snippet: 'after($0)', description: 'Insert after this element' },
    { name: 'replaceWith', snippet: 'replaceWith($0)', description: 'Replace element with another' },
    { name: 'remove', snippet: 'remove()', description: 'Remove element from DOM' },
    { name: 'removeChild', snippet: 'removeChild($0)', description: 'Remove specific child element' },
    { name: 'insertBefore', snippet: 'insertBefore(${1:newNode}, ${2:referenceNode})', description: 'Insert before reference node' },
    { name: 'replaceChild', snippet: 'replaceChild(${1:newNode}, ${2:oldNode})', description: 'Replace child node' },
    { name: 'insertAdjacentElement', snippet: "insertAdjacentElement('${1:beforebegin|afterbegin|beforeend|afterend}', $0)", description: 'Insert element at adjacent position' },
    { name: 'insertAdjacentHTML', snippet: "insertAdjacentHTML('${1:beforeend}', '$0')", description: 'Insert HTML string at adjacent position' },
    { name: 'insertAdjacentText', snippet: "insertAdjacentText('${1:beforeend}', '$0')", description: 'Insert text at adjacent position' },
    { name: 'cloneNode', snippet: 'cloneNode(${1:true})', description: 'Clone node (true = deep clone)' },
    { name: 'contains', snippet: 'contains($0)', description: 'Check if element contains another node' },
    { name: 'normalize', snippet: 'normalize()', description: 'Merge adjacent text nodes in subtree' },
    // Attributes
    { name: 'getAttribute', snippet: "getAttribute('$0')", description: 'Get attribute value' },
    { name: 'setAttribute', snippet: "setAttribute('${1:name}', '${2:value}')", description: 'Set attribute value' },
    { name: 'removeAttribute', snippet: "removeAttribute('$0')", description: 'Remove attribute' },
    { name: 'hasAttribute', snippet: "hasAttribute('$0')", description: 'Check if attribute exists' },
    { name: 'hasAttributes', snippet: 'hasAttributes()', description: 'Check if element has any attributes' },
    { name: 'getAttributeNames', snippet: 'getAttributeNames()', description: 'Get array of all attribute names' },
    { name: 'toggleAttribute', snippet: "toggleAttribute('$0')", description: 'Toggle boolean attribute on/off' },
    { name: 'getAttributeNS', snippet: "getAttributeNS('${1:namespace}', '${2:name}')", description: 'Get namespaced attribute' },
    { name: 'setAttributeNS', snippet: "setAttributeNS('${1:namespace}', '${2:name}', '${3:value}')", description: 'Set namespaced attribute' },
    // Content
    { name: 'innerHTML', snippet: "innerHTML = '$0'", description: 'Set inner HTML' },
    { name: 'outerHTML', snippet: 'outerHTML', description: 'Full HTML of element including itself' },
    { name: 'textContent', snippet: "textContent = '$0'", description: 'Set or get text content (no HTML)' },
    { name: 'innerText', snippet: "innerText = '$0'", description: 'Set or get visible text (respects CSS)' },
    // Styles & classes
    { name: 'classList', snippet: 'classList', description: 'Element class list' },
    { name: 'className', snippet: 'className', description: 'Space-separated class string' },
    { name: 'style', snippet: 'style', description: 'Inline style object' },
    // Form-specific
    { name: 'value', snippet: 'value', description: 'Input/textarea/select value' },
    { name: 'checked', snippet: 'checked', description: 'Checkbox/radio checked state' },
    { name: 'disabled', snippet: 'disabled', description: 'Whether element is disabled' },
    { name: 'readOnly', snippet: 'readOnly', description: 'Whether input is read-only' },
    { name: 'required', snippet: 'required', description: 'Whether field is required' },
    { name: 'selected', snippet: 'selected', description: 'Whether option is selected' },
    { name: 'placeholder', snippet: "placeholder = '$0'", description: 'Input placeholder text' },
    { name: 'maxLength', snippet: 'maxLength', description: 'Max character length' },
    { name: 'selectionStart', snippet: 'selectionStart', description: 'Cursor selection start index' },
    { name: 'selectionEnd', snippet: 'selectionEnd', description: 'Cursor selection end index' },
    { name: 'setSelectionRange', snippet: 'setSelectionRange(${1:start}, ${2:end})', description: 'Set text selection range' },
    { name: 'select', snippet: 'select()', description: 'Select all text in input' },
    // Interaction
    { name: 'focus', snippet: 'focus()', description: 'Focus element' },
    { name: 'blur', snippet: 'blur()', description: 'Remove focus from element' },
    { name: 'click', snippet: 'click()', description: 'Simulate mouse click' },
    { name: 'submit', snippet: 'submit()', description: 'Submit form' },
    { name: 'reset', snippet: 'reset()', description: 'Reset form to defaults' },
    { name: 'requestFullscreen', snippet: 'requestFullscreen()', description: 'Request fullscreen mode' },
    { name: 'requestPointerLock', snippet: 'requestPointerLock()', description: 'Request pointer lock' },
    { name: 'scrollIntoView', snippet: 'scrollIntoView({ behavior: \'${1:smooth}\', block: \'${2:start}\' })', description: 'Scroll element into view' },
    { name: 'scrollTo', snippet: 'scrollTo({ top: ${1:0}, behavior: \'${2:smooth}\' })', description: 'Scroll element to position' },
    { name: 'scrollBy', snippet: 'scrollBy({ top: ${1:100}, behavior: \'${2:smooth}\' })', description: 'Scroll element by amount' },
    // Geometry
    { name: 'getBoundingClientRect', snippet: 'getBoundingClientRect()', description: 'Get element size and viewport position' },
    { name: 'getClientRects', snippet: 'getClientRects()', description: 'Get DOMRectList for all CSS boxes' },
    { name: 'offsetWidth', snippet: 'offsetWidth', description: 'Element width including padding and border' },
    { name: 'offsetHeight', snippet: 'offsetHeight', description: 'Element height including padding and border' },
    { name: 'offsetTop', snippet: 'offsetTop', description: 'Distance from offsetParent top' },
    { name: 'offsetLeft', snippet: 'offsetLeft', description: 'Distance from offsetParent left' },
    { name: 'offsetParent', snippet: 'offsetParent', description: 'Nearest positioned ancestor' },
    { name: 'clientWidth', snippet: 'clientWidth', description: 'Element width including padding (no border)' },
    { name: 'clientHeight', snippet: 'clientHeight', description: 'Element height including padding (no border)' },
    { name: 'clientTop', snippet: 'clientTop', description: 'Top border width' },
    { name: 'clientLeft', snippet: 'clientLeft', description: 'Left border width' },
    { name: 'scrollWidth', snippet: 'scrollWidth', description: 'Full scrollable width' },
    { name: 'scrollHeight', snippet: 'scrollHeight', description: 'Full scrollable height' },
    { name: 'scrollTop', snippet: 'scrollTop', description: 'Vertical scroll position' },
    { name: 'scrollLeft', snippet: 'scrollLeft', description: 'Horizontal scroll position' },
    // Traversal / tree
    { name: 'closest', snippet: "closest('$0')", description: 'Find nearest ancestor matching CSS selector' },
    { name: 'matches', snippet: "matches('$0')", description: 'Check if element matches CSS selector' },
    { name: 'querySelector', snippet: "querySelector('$0')", description: 'Find first matching descendant' },
    { name: 'querySelectorAll', snippet: "querySelectorAll('$0')", description: 'Find all matching descendants' },
    { name: 'getElementsByClassName', snippet: "getElementsByClassName('$0')", description: 'Get descendants by class' },
    { name: 'getElementsByTagName', snippet: "getElementsByTagName('$0')", description: 'Get descendants by tag' },
    { name: 'parentElement', snippet: 'parentElement', description: 'Parent element' },
    { name: 'parentNode', snippet: 'parentNode', description: 'Parent node (may be non-element)' },
    { name: 'children', snippet: 'children', description: 'Live HTMLCollection of child elements' },
    { name: 'childNodes', snippet: 'childNodes', description: 'Live NodeList of all child nodes' },
    { name: 'childElementCount', snippet: 'childElementCount', description: 'Number of child elements' },
    { name: 'firstChild', snippet: 'firstChild', description: 'First child node' },
    { name: 'lastChild', snippet: 'lastChild', description: 'Last child node' },
    { name: 'firstElementChild', snippet: 'firstElementChild', description: 'First child element' },
    { name: 'lastElementChild', snippet: 'lastElementChild', description: 'Last child element' },
    { name: 'nextSibling', snippet: 'nextSibling', description: 'Next sibling node' },
    { name: 'previousSibling', snippet: 'previousSibling', description: 'Previous sibling node' },
    { name: 'nextElementSibling', snippet: 'nextElementSibling', description: 'Next sibling element' },
    { name: 'previousElementSibling', snippet: 'previousElementSibling', description: 'Previous sibling element' },
    // Identity / meta
    { name: 'id', snippet: 'id', description: 'Element ID attribute' },
    { name: 'tagName', snippet: 'tagName', description: 'Uppercase element tag name' },
    { name: 'nodeName', snippet: 'nodeName', description: 'Node name' },
    { name: 'nodeType', snippet: 'nodeType', description: 'Node type constant (1=element, 3=text...)' },
    { name: 'nodeValue', snippet: 'nodeValue', description: 'Node value (for text/comment nodes)' },
    { name: 'namespaceURI', snippet: 'namespaceURI', description: 'Namespace URI of element' },
    { name: 'localName', snippet: 'localName', description: 'Local part of qualified name' },
    { name: 'dataset', snippet: 'dataset.${0:key}', description: 'Access data-* attributes as camelCase object' },
    { name: 'attributes', snippet: 'attributes', description: 'NamedNodeMap of all attributes' },
    { name: 'isConnected', snippet: 'isConnected', description: 'Whether element is in the document' },
    { name: 'ownerDocument', snippet: 'ownerDocument', description: 'The owning document' },
    { name: 'getRootNode', snippet: 'getRootNode()', description: 'Get root node (document or shadow root)' },
    { name: 'isEqualNode', snippet: 'isEqualNode($0)', description: 'Check structural equality with another node' },
    { name: 'isSameNode', snippet: 'isSameNode($0)', description: 'Check if same node reference' },
    { name: 'compareDocumentPosition', snippet: 'compareDocumentPosition($0)', description: 'Compare position of two nodes' },
    // Animation
    { name: 'animate', snippet: "animate([{ ${1:opacity}: '${2:0}' }, { ${1:opacity}: '${3:1}' }], { duration: ${4:300}, easing: '${5:ease}' })", description: 'Web Animations API' },
    { name: 'getAnimations', snippet: 'getAnimations()', description: 'Get active animations on element' },
];

// ── Window methods ─────────────────────────────────────────────────────────────

export const WINDOW_METHODS = [
    { name: 'alert', snippet: "alert('$0')", description: 'Show alert dialog' },
    { name: 'confirm', snippet: "confirm('$0')", description: 'Show confirm dialog, returns boolean' },
    { name: 'prompt', snippet: "prompt('$0')", description: 'Show prompt dialog, returns string or null' },
    { name: 'setTimeout', snippet: 'setTimeout(() => {\n\t$0\n}, ${1:1000})', description: 'Execute callback after delay (ms)' },
    { name: 'setInterval', snippet: 'setInterval(() => {\n\t$0\n}, ${1:1000})', description: 'Execute callback repeatedly every N ms' },
    { name: 'clearTimeout', snippet: 'clearTimeout($0)', description: 'Cancel a setTimeout' },
    { name: 'clearInterval', snippet: 'clearInterval($0)', description: 'Cancel a setInterval' },
    { name: 'requestAnimationFrame', snippet: 'requestAnimationFrame(($0) => {\n\t\n})', description: 'Schedule callback before next repaint' },
    { name: 'cancelAnimationFrame', snippet: 'cancelAnimationFrame($0)', description: 'Cancel animation frame request' },
    { name: 'requestIdleCallback', snippet: 'requestIdleCallback(($0) => {\n\t\n})', description: 'Schedule callback during browser idle time' },
    { name: 'cancelIdleCallback', snippet: 'cancelIdleCallback($0)', description: 'Cancel idle callback' },
    { name: 'open', snippet: "open('${1:url}', '${2:_blank}')", description: 'Open new browser window or tab' },
    { name: 'close', snippet: 'close()', description: 'Close the window' },
    { name: 'focus', snippet: 'focus()', description: 'Focus the window' },
    { name: 'blur', snippet: 'blur()', description: 'Remove focus from window' },
    { name: 'stop', snippet: 'stop()', description: 'Stop loading the page' },
    { name: 'print', snippet: 'print()', description: 'Open print dialog' },
    { name: 'scrollTo', snippet: 'scrollTo(${1:0}, ${2:0})', description: 'Scroll to absolute position' },
    { name: 'scrollBy', snippet: 'scrollBy(${1:0}, ${2:100})', description: 'Scroll by relative amount' },
    { name: 'scroll', snippet: 'scroll({ top: ${1:0}, behavior: \'${2:smooth}\' })', description: 'Scroll with options' },
    { name: 'resizeTo', snippet: 'resizeTo(${1:800}, ${2:600})', description: 'Resize window to dimensions' },
    { name: 'resizeBy', snippet: 'resizeBy(${1:100}, ${2:100})', description: 'Resize window by amount' },
    { name: 'moveTo', snippet: 'moveTo(${1:0}, ${2:0})', description: 'Move window to position' },
    { name: 'moveBy', snippet: 'moveBy(${1:100}, ${2:0})', description: 'Move window by amount' },
    { name: 'postMessage', snippet: "postMessage($1, '${2:*}')", description: 'Send message to another window/frame' },
    { name: 'matchMedia', snippet: "matchMedia('(${1:max-width: 768px})')", description: 'Test a CSS media query' },
    { name: 'getComputedStyle', snippet: 'getComputedStyle($0)', description: 'Get computed styles of element' },
    { name: 'getSelection', snippet: 'getSelection()', description: 'Get current text selection' },
    { name: 'atob', snippet: 'atob($0)', description: 'Decode base64 string' },
    { name: 'btoa', snippet: 'btoa($0)', description: 'Encode string to base64' },
    { name: 'queueMicrotask', snippet: 'queueMicrotask(() => {\n\t$0\n})', description: 'Queue a microtask callback' },
    { name: 'structuredClone', snippet: 'structuredClone($0)', description: 'Deep clone a value' },
    // Properties
    { name: 'innerWidth', snippet: 'innerWidth', description: 'Viewport width (px)' },
    { name: 'innerHeight', snippet: 'innerHeight', description: 'Viewport height (px)' },
    { name: 'outerWidth', snippet: 'outerWidth', description: 'Window outer width including chrome' },
    { name: 'outerHeight', snippet: 'outerHeight', description: 'Window outer height including chrome' },
    { name: 'screenX', snippet: 'screenX', description: 'Window X position on screen' },
    { name: 'screenY', snippet: 'screenY', description: 'Window Y position on screen' },
    { name: 'scrollX', snippet: 'scrollX', description: 'Horizontal scroll position (alias pageXOffset)' },
    { name: 'scrollY', snippet: 'scrollY', description: 'Vertical scroll position (alias pageYOffset)' },
    { name: 'pageXOffset', snippet: 'pageXOffset', description: 'Horizontal scroll position' },
    { name: 'pageYOffset', snippet: 'pageYOffset', description: 'Vertical scroll position' },
    { name: 'devicePixelRatio', snippet: 'devicePixelRatio', description: 'Physical to CSS pixel ratio' },
    { name: 'isSecureContext', snippet: 'isSecureContext', description: 'Whether page is in a secure context (HTTPS)' },
    { name: 'origin', snippet: 'origin', description: 'Window origin (scheme + host + port)' },
    { name: 'name', snippet: 'name', description: 'Window name' },
    { name: 'opener', snippet: 'opener', description: 'Reference to the window that opened this one' },
    { name: 'parent', snippet: 'parent', description: 'Parent window (or self if top-level)' },
    { name: 'top', snippet: 'top', description: 'Top-most window in the hierarchy' },
    { name: 'self', snippet: 'self', description: 'Reference to the window itself' },
    { name: 'frames', snippet: 'frames', description: 'Array-like list of child frames' },
    { name: 'frameElement', snippet: 'frameElement', description: 'The iframe element this window is in (or null)' },
    { name: 'closed', snippet: 'closed', description: 'Whether window has been closed' },
    { name: 'length', snippet: 'length', description: 'Number of frames in window' },
];

// ── Navigator ──────────────────────────────────────────────────────────────────

export const NAVIGATOR_METHODS = [
    { name: 'userAgent', snippet: 'userAgent', description: 'Browser user agent string' },
    { name: 'language', snippet: 'language', description: 'Browser preferred language (e.g. "en-US")' },
    { name: 'languages', snippet: 'languages', description: 'Array of preferred languages' },
    { name: 'platform', snippet: 'platform', description: 'Platform string (deprecated but still used)' },
    { name: 'vendor', snippet: 'vendor', description: 'Browser vendor string' },
    { name: 'appName', snippet: 'appName', description: 'Browser application name (usually "Netscape")' },
    { name: 'appVersion', snippet: 'appVersion', description: 'Browser version string' },
    { name: 'cookieEnabled', snippet: 'cookieEnabled', description: 'Whether cookies are enabled' },
    { name: 'onLine', snippet: 'onLine', description: 'Whether browser is online' },
    { name: 'hardwareConcurrency', snippet: 'hardwareConcurrency', description: 'Number of logical CPU cores' },
    { name: 'maxTouchPoints', snippet: 'maxTouchPoints', description: 'Maximum simultaneous touch points' },
    { name: 'doNotTrack', snippet: 'doNotTrack', description: 'User "Do Not Track" preference' },
    { name: 'geolocation', snippet: 'geolocation', description: 'Geolocation API object' },
    { name: 'clipboard', snippet: 'clipboard', description: 'Clipboard API object' },
    { name: 'permissions', snippet: 'permissions', description: 'Permissions API object' },
    { name: 'serviceWorker', snippet: 'serviceWorker', description: 'Service Worker registration' },
    { name: 'storage', snippet: 'storage', description: 'StorageManager API' },
    { name: 'mediaDevices', snippet: 'mediaDevices', description: 'Media devices (camera, mic) API' },
    { name: 'connection', snippet: 'connection', description: 'Network Information API' },
    { name: 'sendBeacon', snippet: "sendBeacon('${1:url}', $0)", description: 'Send data reliably on page unload' },
    { name: 'vibrate', snippet: 'vibrate(${1:200})', description: 'Vibrate device (ms pattern)' },
    { name: 'share', snippet: "share({ title: '${1:Title}', text: '${2:text}', url: '${3:url}' })", description: 'Web Share API' },
    { name: 'canShare', snippet: "canShare({ url: '$0' })", description: 'Check if Web Share is supported' },
    { name: 'registerProtocolHandler', snippet: "registerProtocolHandler('${1:web+app}', '${2:url}', '${3:title}')", description: 'Register custom protocol handler' },
];

// ── Screen ─────────────────────────────────────────────────────────────────────

export const SCREEN_METHODS = [
    { name: 'width', snippet: 'width', description: 'Total screen width in pixels' },
    { name: 'height', snippet: 'height', description: 'Total screen height in pixels' },
    { name: 'availWidth', snippet: 'availWidth', description: 'Available screen width (excluding taskbar)' },
    { name: 'availHeight', snippet: 'availHeight', description: 'Available screen height (excluding taskbar)' },
    { name: 'colorDepth', snippet: 'colorDepth', description: 'Screen color depth in bits' },
    { name: 'pixelDepth', snippet: 'pixelDepth', description: 'Screen pixel depth in bits' },
    { name: 'orientation', snippet: 'orientation', description: 'Screen orientation object' },
];

// ── Performance ────────────────────────────────────────────────────────────────

export const PERFORMANCE_METHODS = [
    { name: 'now', snippet: 'now()', description: 'High-resolution timestamp in ms' },
    { name: 'mark', snippet: "mark('${1:start}')", description: 'Create named performance mark' },
    { name: 'measure', snippet: "measure('${1:name}', '${2:startMark}', '${3:endMark}')", description: 'Measure between two marks' },
    { name: 'getEntries', snippet: 'getEntries()', description: 'Get all performance entries' },
    { name: 'getEntriesByName', snippet: "getEntriesByName('$0')", description: 'Get entries by name' },
    { name: 'getEntriesByType', snippet: "getEntriesByType('${1:navigation}')", description: 'Get entries by type' },
    { name: 'clearMarks', snippet: 'clearMarks()', description: 'Clear all marks' },
    { name: 'clearMeasures', snippet: 'clearMeasures()', description: 'Clear all measures' },
    { name: 'clearResourceTimings', snippet: 'clearResourceTimings()', description: 'Clear resource timing entries' },
    { name: 'timing', snippet: 'timing', description: 'Legacy performance timing object' },
    { name: 'navigation', snippet: 'navigation', description: 'Navigation type and redirect info' },
    { name: 'memory', snippet: 'memory', description: 'Memory usage info (Chrome only)' },
    { name: 'timeOrigin', snippet: 'timeOrigin', description: 'Start time of the performance clock' },
    { name: 'toJSON', snippet: 'toJSON()', description: 'Serialize performance object to JSON' },
];

// ── Date methods ───────────────────────────────────────────────────────────────

export const DATE_METHODS = [
    // Getters
    { name: 'getFullYear', snippet: 'getFullYear()', description: 'Get 4-digit year' },
    { name: 'getMonth', snippet: 'getMonth()', description: 'Get month (0–11)' },
    { name: 'getDate', snippet: 'getDate()', description: 'Get day of month (1–31)' },
    { name: 'getDay', snippet: 'getDay()', description: 'Get day of week (0=Sun–6=Sat)' },
    { name: 'getHours', snippet: 'getHours()', description: 'Get hour (0–23)' },
    { name: 'getMinutes', snippet: 'getMinutes()', description: 'Get minutes (0–59)' },
    { name: 'getSeconds', snippet: 'getSeconds()', description: 'Get seconds (0–59)' },
    { name: 'getMilliseconds', snippet: 'getMilliseconds()', description: 'Get milliseconds (0–999)' },
    { name: 'getTime', snippet: 'getTime()', description: 'Get Unix timestamp in ms' },
    { name: 'getTimezoneOffset', snippet: 'getTimezoneOffset()', description: 'Get UTC offset in minutes' },
    // UTC getters
    { name: 'getUTCFullYear', snippet: 'getUTCFullYear()', description: 'Get UTC year' },
    { name: 'getUTCMonth', snippet: 'getUTCMonth()', description: 'Get UTC month' },
    { name: 'getUTCDate', snippet: 'getUTCDate()', description: 'Get UTC day' },
    { name: 'getUTCHours', snippet: 'getUTCHours()', description: 'Get UTC hours' },
    { name: 'getUTCMinutes', snippet: 'getUTCMinutes()', description: 'Get UTC minutes' },
    { name: 'getUTCSeconds', snippet: 'getUTCSeconds()', description: 'Get UTC seconds' },
    // Setters
    { name: 'setFullYear', snippet: 'setFullYear(${1:year})', description: 'Set year' },
    { name: 'setMonth', snippet: 'setMonth(${1:month})', description: 'Set month (0–11)' },
    { name: 'setDate', snippet: 'setDate(${1:day})', description: 'Set day of month' },
    { name: 'setHours', snippet: 'setHours(${1:hours})', description: 'Set hours' },
    { name: 'setMinutes', snippet: 'setMinutes(${1:minutes})', description: 'Set minutes' },
    { name: 'setSeconds', snippet: 'setSeconds(${1:seconds})', description: 'Set seconds' },
    { name: 'setMilliseconds', snippet: 'setMilliseconds(${1:ms})', description: 'Set milliseconds' },
    { name: 'setTime', snippet: 'setTime(${1:timestamp})', description: 'Set time from Unix timestamp (ms)' },
    // Formatting
    { name: 'toString', snippet: 'toString()', description: 'Full date/time as string' },
    { name: 'toISOString', snippet: 'toISOString()', description: 'ISO 8601 format (e.g. 2025-01-01T00:00:00.000Z)' },
    { name: 'toLocaleDateString', snippet: "toLocaleDateString('${1:en-US}')", description: 'Locale-sensitive date string' },
    { name: 'toLocaleTimeString', snippet: "toLocaleTimeString('${1:en-US}')", description: 'Locale-sensitive time string' },
    { name: 'toLocaleString', snippet: "toLocaleString('${1:en-US}')", description: 'Locale-sensitive date and time string' },
    { name: 'toDateString', snippet: 'toDateString()', description: 'Human-readable date (e.g. "Mon Jan 01 2025")' },
    { name: 'toTimeString', snippet: 'toTimeString()', description: 'Human-readable time string' },
    { name: 'toUTCString', snippet: 'toUTCString()', description: 'Date in UTC string format' },
    { name: 'toJSON', snippet: 'toJSON()', description: 'Same as toISOString (used in JSON.stringify)' },
    { name: 'valueOf', snippet: 'valueOf()', description: 'Numeric timestamp value' },
    // Static
    { name: 'Date.now', snippet: 'Date.now()', description: 'Current Unix timestamp in ms (static)' },
    { name: 'Date.parse', snippet: "Date.parse('$0')", description: 'Parse date string to timestamp' },
    { name: 'Date.UTC', snippet: 'Date.UTC(${1:year}, ${2:month}, ${3:day})', description: 'Create UTC timestamp from components' },
];

// ── Number methods ─────────────────────────────────────────────────────────────

export const NUMBER_METHODS = [
    { name: 'toFixed', snippet: 'toFixed(${1:2})', description: 'Format to N decimal places (returns string)' },
    { name: 'toPrecision', snippet: 'toPrecision(${1:4})', description: 'Format to N significant digits' },
    { name: 'toExponential', snippet: 'toExponential(${1:2})', description: 'Format in exponential notation' },
    { name: 'toString', snippet: 'toString(${1:10})', description: 'Convert to string with optional radix' },
    { name: 'toLocaleString', snippet: "toLocaleString('${1:en-US}')", description: 'Locale-sensitive number string' },
    { name: 'valueOf', snippet: 'valueOf()', description: 'Primitive number value' },
    // Static
    { name: 'Number.isNaN', snippet: 'Number.isNaN($0)', description: 'True only for actual NaN (not coerced)' },
    { name: 'Number.isFinite', snippet: 'Number.isFinite($0)', description: 'True if finite (not coerced)' },
    { name: 'Number.isInteger', snippet: 'Number.isInteger($0)', description: 'Check if value is an integer' },
    { name: 'Number.isSafeInteger', snippet: 'Number.isSafeInteger($0)', description: 'Check if value is a safe integer' },
    { name: 'Number.parseInt', snippet: 'Number.parseInt($0)', description: 'Parse to integer' },
    { name: 'Number.parseFloat', snippet: 'Number.parseFloat($0)', description: 'Parse to float' },
    { name: 'Number.MAX_VALUE', snippet: 'Number.MAX_VALUE', description: 'Largest representable number' },
    { name: 'Number.MIN_VALUE', snippet: 'Number.MIN_VALUE', description: 'Smallest positive number' },
    { name: 'Number.MAX_SAFE_INTEGER', snippet: 'Number.MAX_SAFE_INTEGER', description: '2^53 - 1' },
    { name: 'Number.MIN_SAFE_INTEGER', snippet: 'Number.MIN_SAFE_INTEGER', description: '-(2^53 - 1)' },
    { name: 'Number.POSITIVE_INFINITY', snippet: 'Number.POSITIVE_INFINITY', description: 'Positive infinity constant' },
    { name: 'Number.NEGATIVE_INFINITY', snippet: 'Number.NEGATIVE_INFINITY', description: 'Negative infinity constant' },
    { name: 'Number.NaN', snippet: 'Number.NaN', description: 'NaN constant' },
    { name: 'Number.EPSILON', snippet: 'Number.EPSILON', description: 'Difference between 1 and smallest float > 1' },
];

// ── Math methods ───────────────────────────────────────────────────────────────

export const MATH_METHODS = [
    { name: 'round', snippet: 'round($0)', description: 'Round to nearest integer' },
    { name: 'floor', snippet: 'floor($0)', description: 'Round down (toward -∞)' },
    { name: 'ceil', snippet: 'ceil($0)', description: 'Round up (toward +∞)' },
    { name: 'trunc', snippet: 'trunc($0)', description: 'Remove fractional part (toward 0)' },
    { name: 'abs', snippet: 'abs($0)', description: 'Absolute value' },
    { name: 'max', snippet: 'max($0)', description: 'Largest of values' },
    { name: 'min', snippet: 'min($0)', description: 'Smallest of values' },
    { name: 'random', snippet: 'random()', description: 'Random float in [0, 1)' },
    { name: 'pow', snippet: 'pow(${1:base}, ${2:exponent})', description: 'Raise base to power' },
    { name: 'sqrt', snippet: 'sqrt($0)', description: 'Square root' },
    { name: 'cbrt', snippet: 'cbrt($0)', description: 'Cube root' },
    { name: 'hypot', snippet: 'hypot($0)', description: 'Hypotenuse of values (Euclidean distance)' },
    { name: 'exp', snippet: 'exp($0)', description: 'e raised to given power' },
    { name: 'expm1', snippet: 'expm1($0)', description: 'e^x - 1 (more precise for small x)' },
    { name: 'log', snippet: 'log($0)', description: 'Natural logarithm (base e)' },
    { name: 'log2', snippet: 'log2($0)', description: 'Logarithm base 2' },
    { name: 'log10', snippet: 'log10($0)', description: 'Logarithm base 10' },
    { name: 'log1p', snippet: 'log1p($0)', description: 'ln(1 + x) (more precise for small x)' },
    { name: 'sign', snippet: 'sign($0)', description: 'Sign of number: -1, 0, or 1' },
    { name: 'clz32', snippet: 'clz32($0)', description: 'Count leading zero bits in 32-bit int' },
    { name: 'fround', snippet: 'fround($0)', description: 'Nearest 32-bit float representation' },
    { name: 'imul', snippet: 'imul(${1:a}, ${2:b})', description: '32-bit integer multiplication' },
    // Trig
    { name: 'sin', snippet: 'sin($0)', description: 'Sine (radians)' },
    { name: 'cos', snippet: 'cos($0)', description: 'Cosine (radians)' },
    { name: 'tan', snippet: 'tan($0)', description: 'Tangent (radians)' },
    { name: 'asin', snippet: 'asin($0)', description: 'Arcsine in radians' },
    { name: 'acos', snippet: 'acos($0)', description: 'Arccosine in radians' },
    { name: 'atan', snippet: 'atan($0)', description: 'Arctangent in radians' },
    { name: 'atan2', snippet: 'atan2(${1:y}, ${2:x})', description: 'Angle from X-axis to point (y, x)' },
    { name: 'sinh', snippet: 'sinh($0)', description: 'Hyperbolic sine' },
    { name: 'cosh', snippet: 'cosh($0)', description: 'Hyperbolic cosine' },
    { name: 'tanh', snippet: 'tanh($0)', description: 'Hyperbolic tangent' },
    { name: 'asinh', snippet: 'asinh($0)', description: 'Inverse hyperbolic sine' },
    { name: 'acosh', snippet: 'acosh($0)', description: 'Inverse hyperbolic cosine' },
    { name: 'atanh', snippet: 'atanh($0)', description: 'Inverse hyperbolic tangent' },
    // Constants
    { name: 'PI', snippet: 'PI', description: 'π ≈ 3.14159' },
    { name: 'E', snippet: 'E', description: "Euler's number ≈ 2.71828" },
    { name: 'LN2', snippet: 'LN2', description: 'Natural log of 2 ≈ 0.693' },
    { name: 'LN10', snippet: 'LN10', description: 'Natural log of 10 ≈ 2.303' },
    { name: 'LOG2E', snippet: 'LOG2E', description: 'Log base 2 of e ≈ 1.443' },
    { name: 'LOG10E', snippet: 'LOG10E', description: 'Log base 10 of e ≈ 0.434' },
    { name: 'SQRT2', snippet: 'SQRT2', description: 'Square root of 2 ≈ 1.414' },
    { name: 'SQRT1_2', snippet: 'SQRT1_2', description: 'Square root of 1/2 ≈ 0.707' },
];

// ── Map methods ────────────────────────────────────────────────────────────────

export const MAP_METHODS = [
    { name: 'set', snippet: 'set(${1:key}, ${2:value})', description: 'Set a key-value pair' },
    { name: 'get', snippet: 'get(${1:key})', description: 'Get value by key' },
    { name: 'has', snippet: 'has(${1:key})', description: 'Check if key exists' },
    { name: 'delete', snippet: 'delete(${1:key})', description: 'Remove key-value pair' },
    { name: 'clear', snippet: 'clear()', description: 'Remove all entries' },
    { name: 'size', snippet: 'size', description: 'Number of entries' },
    { name: 'keys', snippet: 'keys()', description: 'Iterator of all keys' },
    { name: 'values', snippet: 'values()', description: 'Iterator of all values' },
    { name: 'entries', snippet: 'entries()', description: 'Iterator of [key, value] pairs' },
    { name: 'forEach', snippet: 'forEach((${1:value}, ${2:key}) => {\n\t$0\n})', description: 'Iterate over all entries' },
];

// ── Set methods ────────────────────────────────────────────────────────────────

export const SET_METHODS = [
    { name: 'add', snippet: 'add($0)', description: 'Add a value to the set' },
    { name: 'has', snippet: 'has($0)', description: 'Check if value exists' },
    { name: 'delete', snippet: 'delete($0)', description: 'Remove a value' },
    { name: 'clear', snippet: 'clear()', description: 'Remove all values' },
    { name: 'size', snippet: 'size', description: 'Number of values' },
    { name: 'keys', snippet: 'keys()', description: 'Iterator of values (same as values())' },
    { name: 'values', snippet: 'values()', description: 'Iterator of all values' },
    { name: 'entries', snippet: 'entries()', description: 'Iterator of [value, value] pairs' },
    { name: 'forEach', snippet: 'forEach((${1:value}) => {\n\t$0\n})', description: 'Iterate over all values' },
];

// ── Promise methods ────────────────────────────────────────────────────────────

export const PROMISE_METHODS = [
    { name: 'then', snippet: 'then((${1:result}) => {\n\t$0\n})', description: 'Handle fulfilled promise' },
    { name: 'catch', snippet: 'catch((${1:error}) => {\n\t$0\n})', description: 'Handle rejected promise' },
    { name: 'finally', snippet: 'finally(() => {\n\t$0\n})', description: 'Run after fulfilled or rejected' },
    { name: 'Promise.resolve', snippet: 'Promise.resolve($0)', description: 'Create resolved promise' },
    { name: 'Promise.reject', snippet: 'Promise.reject($0)', description: 'Create rejected promise' },
    { name: 'Promise.all', snippet: 'Promise.all([$0])', description: 'Resolve when all resolve; reject on first rejection' },
    { name: 'Promise.allSettled', snippet: 'Promise.allSettled([$0])', description: 'Resolve with all results regardless of rejection' },
    { name: 'Promise.any', snippet: 'Promise.any([$0])', description: 'Resolve with first fulfilled promise' },
    { name: 'Promise.race', snippet: 'Promise.race([$0])', description: 'Settle with first settled promise' },
];

// ── RegExp methods ─────────────────────────────────────────────────────────────

export const REGEXP_METHODS = [
    { name: 'test', snippet: 'test($0)', description: 'Test if string matches regex, returns boolean' },
    { name: 'exec', snippet: 'exec($0)', description: 'Execute regex on string, returns match array or null' },
    { name: 'source', snippet: 'source', description: 'The regex pattern text' },
    { name: 'flags', snippet: 'flags', description: 'All flags as a string (e.g. "gi")' },
    { name: 'global', snippet: 'global', description: 'Whether g flag is set' },
    { name: 'ignoreCase', snippet: 'ignoreCase', description: 'Whether i flag is set' },
    { name: 'multiline', snippet: 'multiline', description: 'Whether m flag is set' },
    { name: 'sticky', snippet: 'sticky', description: 'Whether y flag is set' },
    { name: 'unicode', snippet: 'unicode', description: 'Whether u flag is set' },
    { name: 'dotAll', snippet: 'dotAll', description: 'Whether s flag is set' },
    { name: 'lastIndex', snippet: 'lastIndex', description: 'Index at which to start next match (for g/y flags)' },
];

// ── URLSearchParams methods ────────────────────────────────────────────────────

export const URL_SEARCH_PARAMS_METHODS = [
    { name: 'get', snippet: "get('$0')", description: 'Get first value for key' },
    { name: 'getAll', snippet: "getAll('$0')", description: 'Get all values for key' },
    { name: 'has', snippet: "has('$0')", description: 'Check if key exists' },
    { name: 'set', snippet: "set('${1:key}', '${2:value}')", description: 'Set value for key (replaces all)' },
    { name: 'append', snippet: "append('${1:key}', '${2:value}')", description: 'Append value for key' },
    { name: 'delete', snippet: "delete('$0')", description: 'Delete all values for key' },
    { name: 'keys', snippet: 'keys()', description: 'Iterator of all keys' },
    { name: 'values', snippet: 'values()', description: 'Iterator of all values' },
    { name: 'entries', snippet: 'entries()', description: 'Iterator of [key, value] pairs' },
    { name: 'forEach', snippet: 'forEach((${1:value}, ${2:key}) => {\n\t$0\n})', description: 'Iterate over all entries' },
    { name: 'toString', snippet: 'toString()', description: 'Serialize back to query string' },
    { name: 'sort', snippet: 'sort()', description: 'Sort parameters by key' },
    { name: 'size', snippet: 'size', description: 'Number of parameters (modern browsers)' },
];

// ── FormData methods ───────────────────────────────────────────────────────────

export const FORM_DATA_METHODS = [
    { name: 'append', snippet: "append('${1:name}', $0)", description: 'Append value under key' },
    { name: 'set', snippet: "set('${1:name}', $0)", description: 'Set (replace) value for key' },
    { name: 'get', snippet: "get('$0')", description: 'Get first value for key' },
    { name: 'getAll', snippet: "getAll('$0')", description: 'Get all values for key' },
    { name: 'has', snippet: "has('$0')", description: 'Check if key exists' },
    { name: 'delete', snippet: "delete('$0')", description: 'Remove all values for key' },
    { name: 'keys', snippet: 'keys()', description: 'Iterator of all keys' },
    { name: 'values', snippet: 'values()', description: 'Iterator of all values' },
    { name: 'entries', snippet: 'entries()', description: 'Iterator of [key, value] pairs' },
    { name: 'forEach', snippet: 'forEach((${1:value}, ${2:key}) => {\n\t$0\n})', description: 'Iterate over all entries' },
];

// ── Fetch / Response methods ───────────────────────────────────────────────────

export const RESPONSE_METHODS = [
    { name: 'json', snippet: 'json()', description: 'Parse body as JSON (returns Promise)' },
    { name: 'text', snippet: 'text()', description: 'Read body as plain text (returns Promise)' },
    { name: 'blob', snippet: 'blob()', description: 'Read body as Blob (returns Promise)' },
    { name: 'arrayBuffer', snippet: 'arrayBuffer()', description: 'Read body as ArrayBuffer (returns Promise)' },
    { name: 'formData', snippet: 'formData()', description: 'Read body as FormData (returns Promise)' },
    { name: 'clone', snippet: 'clone()', description: 'Clone response (body can only be read once)' },
    { name: 'ok', snippet: 'ok', description: 'True if status is 200–299' },
    { name: 'status', snippet: 'status', description: 'HTTP status code (e.g. 200, 404)' },
    { name: 'statusText', snippet: 'statusText', description: 'Status text (e.g. "OK")' },
    { name: 'url', snippet: 'url', description: 'Final URL after redirects' },
    { name: 'headers', snippet: 'headers', description: 'Response Headers object' },
    { name: 'redirected', snippet: 'redirected', description: 'Whether response was redirected' },
    { name: 'type', snippet: 'type', description: 'Response type: basic, cors, opaque...' },
    { name: 'body', snippet: 'body', description: 'ReadableStream of body content' },
    { name: 'bodyUsed', snippet: 'bodyUsed', description: 'Whether body has already been consumed' },
];

// ── MutationObserver ───────────────────────────────────────────────────────────

export const MUTATION_OBSERVER_METHODS = [
    { name: 'observe', snippet: "observe(${1:targetNode}, {\n\tattributes: true,\n\tchildList: true,\n\tsubtree: ${2:false}\n})", description: 'Start observing target node for mutations' },
    { name: 'disconnect', snippet: 'disconnect()', description: 'Stop observing all targets' },
    { name: 'takeRecords', snippet: 'takeRecords()', description: 'Return pending mutation records and clear queue' },
];

// ── IntersectionObserver ───────────────────────────────────────────────────────

export const INTERSECTION_OBSERVER_METHODS = [
    { name: 'observe', snippet: 'observe($0)', description: 'Start observing element for intersection' },
    { name: 'unobserve', snippet: 'unobserve($0)', description: 'Stop observing specific element' },
    { name: 'disconnect', snippet: 'disconnect()', description: 'Stop observing all elements' },
    { name: 'takeRecords', snippet: 'takeRecords()', description: 'Return pending intersection records' },
];

// ── Event object properties (inside event handlers) ───────────────────────────

export const EVENT_METHODS = [
    { name: 'preventDefault', snippet: 'preventDefault()', description: 'Prevent default browser behavior' },
    { name: 'stopPropagation', snippet: 'stopPropagation()', description: 'Stop event from bubbling up' },
    { name: 'stopImmediatePropagation', snippet: 'stopImmediatePropagation()', description: 'Stop propagation and other same-element listeners' },
    { name: 'target', snippet: 'target', description: 'Element that triggered the event' },
    { name: 'currentTarget', snippet: 'currentTarget', description: 'Element the listener is attached to' },
    { name: 'relatedTarget', snippet: 'relatedTarget', description: 'Secondary target (mouseover/out, focus/blur)' },
    { name: 'type', snippet: 'type', description: 'Event type string (e.g. "click")' },
    { name: 'timeStamp', snippet: 'timeStamp', description: 'Time event was created (ms since origin)' },
    { name: 'bubbles', snippet: 'bubbles', description: 'Whether event bubbles up' },
    { name: 'cancelable', snippet: 'cancelable', description: 'Whether default can be prevented' },
    { name: 'defaultPrevented', snippet: 'defaultPrevented', description: 'Whether preventDefault was called' },
    { name: 'isTrusted', snippet: 'isTrusted', description: 'True if dispatched by user, false if by script' },
    { name: 'eventPhase', snippet: 'eventPhase', description: 'Current phase: 0=none, 1=capture, 2=target, 3=bubble' },
    { name: 'composed', snippet: 'composed', description: 'Whether event can cross shadow DOM boundary' },
    // Mouse/pointer
    { name: 'clientX', snippet: 'clientX', description: 'Mouse X relative to viewport' },
    { name: 'clientY', snippet: 'clientY', description: 'Mouse Y relative to viewport' },
    { name: 'pageX', snippet: 'pageX', description: 'Mouse X relative to document (includes scroll)' },
    { name: 'pageY', snippet: 'pageY', description: 'Mouse Y relative to document (includes scroll)' },
    { name: 'screenX', snippet: 'screenX', description: 'Mouse X relative to screen' },
    { name: 'screenY', snippet: 'screenY', description: 'Mouse Y relative to screen' },
    { name: 'offsetX', snippet: 'offsetX', description: 'Mouse X relative to target element' },
    { name: 'offsetY', snippet: 'offsetY', description: 'Mouse Y relative to target element' },
    { name: 'movementX', snippet: 'movementX', description: 'Mouse X movement since last event' },
    { name: 'movementY', snippet: 'movementY', description: 'Mouse Y movement since last event' },
    { name: 'button', snippet: 'button', description: 'Mouse button: 0=left, 1=middle, 2=right' },
    { name: 'buttons', snippet: 'buttons', description: 'Bitmask of pressed buttons' },
    { name: 'altKey', snippet: 'altKey', description: 'Whether Alt key was held' },
    { name: 'ctrlKey', snippet: 'ctrlKey', description: 'Whether Ctrl key was held' },
    { name: 'shiftKey', snippet: 'shiftKey', description: 'Whether Shift key was held' },
    { name: 'metaKey', snippet: 'metaKey', description: 'Whether Meta/Command key was held' },
    { name: 'detail', snippet: 'detail', description: 'Click count for mouse events' },
    // Keyboard
    { name: 'key', snippet: 'key', description: 'Key value string (e.g. "Enter", "a")' },
    { name: 'code', snippet: 'code', description: 'Physical key code (e.g. "KeyA", "Space")' },
    { name: 'keyCode', snippet: 'keyCode', description: 'Key code (deprecated, use key/code)' },
    { name: 'charCode', snippet: 'charCode', description: 'Character code (deprecated)' },
    { name: 'which', snippet: 'which', description: 'Key/button code (deprecated)' },
    { name: 'repeat', snippet: 'repeat', description: 'True if key is held down and repeating' },
    { name: 'isComposing', snippet: 'isComposing', description: 'True during IME composition' },
    // Input / data
    { name: 'data', snippet: 'data', description: 'Inserted characters (input events)' },
    { name: 'inputType', snippet: 'inputType', description: 'How the input was triggered (e.g. "insertText")' },
    // Drag
    { name: 'dataTransfer', snippet: 'dataTransfer', description: 'Drag-and-drop data transfer object' },
    // Touch
    { name: 'touches', snippet: 'touches', description: 'All current touch points (TouchList)' },
    { name: 'targetTouches', snippet: 'targetTouches', description: 'Touch points on the target element' },
    { name: 'changedTouches', snippet: 'changedTouches', description: 'Touch points that changed in this event' },
    // Scroll / wheel
    { name: 'deltaX', snippet: 'deltaX', description: 'Horizontal wheel delta' },
    { name: 'deltaY', snippet: 'deltaY', description: 'Vertical wheel delta' },
    { name: 'deltaZ', snippet: 'deltaZ', description: 'Z-axis wheel delta' },
    { name: 'deltaMode', snippet: 'deltaMode', description: 'Delta unit: 0=pixel, 1=line, 2=page' },
];

// ── Global functions ───────────────────────────────────────────────────────────

export const JS_GLOBAL_FUNCTIONS = [
    { name: 'parseInt', snippet: 'parseInt($0)', description: 'Parse string to integer' },
    { name: 'parseFloat', snippet: 'parseFloat($0)', description: 'Parse string to float' },
    { name: 'isNaN', snippet: 'isNaN($0)', description: 'Check if value coerces to NaN' },
    { name: 'isFinite', snippet: 'isFinite($0)', description: 'Check if value coerces to finite number' },
    { name: 'Number', snippet: 'Number($0)', description: 'Convert to number' },
    { name: 'String', snippet: 'String($0)', description: 'Convert to string' },
    { name: 'Boolean', snippet: 'Boolean($0)', description: 'Convert to boolean' },
    { name: 'BigInt', snippet: 'BigInt($0)', description: 'Create BigInt from value' },
    { name: 'Symbol', snippet: "Symbol('$0')", description: 'Create unique Symbol' },
    { name: 'JSON.parse', snippet: 'JSON.parse($0)', description: 'Parse JSON string to value' },
    { name: 'JSON.stringify', snippet: 'JSON.stringify(${1:obj}, ${2:null}, ${3:2})', description: 'Convert value to JSON string' },
    { name: 'Math.round', snippet: 'Math.round($0)', description: 'Round to nearest integer' },
    { name: 'Math.floor', snippet: 'Math.floor($0)', description: 'Round down' },
    { name: 'Math.ceil', snippet: 'Math.ceil($0)', description: 'Round up' },
    { name: 'Math.abs', snippet: 'Math.abs($0)', description: 'Absolute value' },
    { name: 'Math.max', snippet: 'Math.max($0)', description: 'Maximum value' },
    { name: 'Math.min', snippet: 'Math.min($0)', description: 'Minimum value' },
    { name: 'Math.random', snippet: 'Math.random()', description: 'Random float in [0, 1)' },
    { name: 'Math.pow', snippet: 'Math.pow(${1:base}, ${2:exponent})', description: 'Power' },
    { name: 'Math.sqrt', snippet: 'Math.sqrt($0)', description: 'Square root' },
    { name: 'Math.trunc', snippet: 'Math.trunc($0)', description: 'Remove decimal part' },
    { name: 'Math.sign', snippet: 'Math.sign($0)', description: 'Sign: -1, 0, or 1' },
    { name: 'Math.PI', snippet: 'Math.PI', description: 'π constant' },
    { name: 'Date.now', snippet: 'Date.now()', description: 'Current timestamp in ms' },
    { name: 'new Date', snippet: 'new Date()', description: 'Create Date object' },
    { name: 'encodeURIComponent', snippet: 'encodeURIComponent($0)', description: 'Encode URI component' },
    { name: 'decodeURIComponent', snippet: 'decodeURIComponent($0)', description: 'Decode URI component' },
    { name: 'encodeURI', snippet: 'encodeURI($0)', description: 'Encode full URI' },
    { name: 'decodeURI', snippet: 'decodeURI($0)', description: 'Decode full URI' },
    { name: 'atob', snippet: 'atob($0)', description: 'Decode base64 string' },
    { name: 'btoa', snippet: 'btoa($0)', description: 'Encode string to base64' },
    { name: 'structuredClone', snippet: 'structuredClone($0)', description: 'Deep clone a value' },
    { name: 'queueMicrotask', snippet: 'queueMicrotask(() => {\n\t$0\n})', description: 'Queue a microtask' },
    { name: 'fetch', snippet: "fetch('${1:url}')\n\t.then(res => res.json())\n\t.then(data => {\n\t\t$0\n\t})\n\t.catch(err => console.error(err))", description: 'HTTP request via Fetch API' },
    { name: 'fetch async', snippet: "const response = await fetch('${1:url}');\nconst data = await response.json();\n$0", description: 'Fetch with async/await' },
    { name: 'fetch POST', snippet: "const response = await fetch('${1:url}', {\n\tmethod: 'POST',\n\theaders: { 'Content-Type': 'application/json' },\n\tbody: JSON.stringify($0)\n});\nconst data = await response.json();", description: 'Fetch POST with JSON body' },
    { name: 'Promise', snippet: 'new Promise((resolve, reject) => {\n\t$0\n})', description: 'Create a Promise' },
    { name: 'Promise.all', snippet: 'Promise.all([$0])', description: 'Resolve when all resolve' },
    { name: 'Promise.allSettled', snippet: 'Promise.allSettled([$0])', description: 'Resolve with all results' },
    { name: 'Promise.any', snippet: 'Promise.any([$0])', description: 'Resolve with first fulfilled' },
    { name: 'Promise.race', snippet: 'Promise.race([$0])', description: 'Settle with first settled' },
    { name: 'Promise.resolve', snippet: 'Promise.resolve($0)', description: 'Create resolved promise' },
    { name: 'Promise.reject', snippet: 'Promise.reject($0)', description: 'Create rejected promise' },
    { name: 'new MutationObserver', snippet: "new MutationObserver((mutations) => {\n\tmutations.forEach(mutation => {\n\t\t$0\n\t});\n})", description: 'Create MutationObserver' },
    { name: 'new IntersectionObserver', snippet: "new IntersectionObserver((entries) => {\n\tentries.forEach(entry => {\n\t\tif (entry.isIntersecting) {\n\t\t\t$0\n\t\t}\n\t});\n}, { threshold: ${1:0.1} })", description: 'Create IntersectionObserver' },
    { name: 'new ResizeObserver', snippet: "new ResizeObserver((entries) => {\n\tentries.forEach(entry => {\n\t\t$0\n\t});\n})", description: 'Create ResizeObserver' },
    { name: 'new URLSearchParams', snippet: "new URLSearchParams($0)", description: 'Parse or build query string' },
    { name: 'new FormData', snippet: 'new FormData($0)', description: 'Create FormData (optionally from form element)' },
    { name: 'new URL', snippet: "new URL('$0')", description: 'Parse a URL string' },
    { name: 'new AbortController', snippet: 'new AbortController()', description: 'Create abort controller for cancellable fetch' },
    { name: 'new Worker', snippet: "new Worker('${1:worker.js}')", description: 'Create a Web Worker' },
    { name: 'new EventSource', snippet: "new EventSource('${1:url}')", description: 'Server-Sent Events connection' },
    { name: 'new WebSocket', snippet: "new WebSocket('${1:ws://url}')", description: 'Open a WebSocket connection' },
    { name: 'new CustomEvent', snippet: "new CustomEvent('${1:eventName}', { detail: $0 })", description: 'Create a custom DOM event with data' },
    { name: 'new Error', snippet: "new Error('$0')", description: 'Create Error object' },
    { name: 'new TypeError', snippet: "new TypeError('$0')", description: 'Create TypeError object' },
    { name: 'new RangeError', snippet: "new RangeError('$0')", description: 'Create RangeError object' },
    { name: 'new Map', snippet: 'new Map()', description: 'Create a Map' },
    { name: 'new Set', snippet: 'new Set()', description: 'Create a Set' },
    { name: 'new WeakMap', snippet: 'new WeakMap()', description: 'Create a WeakMap' },
    { name: 'new WeakSet', snippet: 'new WeakSet()', description: 'Create a WeakSet' },
    { name: 'new Proxy', snippet: "new Proxy(${1:target}, {\n\tget(target, key) { return $0; }\n})", description: 'Create a Proxy object' },
    { name: 'Object.keys', snippet: 'Object.keys($0)', description: 'Get enumerable own property keys' },
    { name: 'Object.values', snippet: 'Object.values($0)', description: 'Get enumerable own property values' },
    { name: 'Object.entries', snippet: 'Object.entries($0)', description: 'Get [key, value] pairs' },
    { name: 'Object.assign', snippet: 'Object.assign(${1:{}}, $0)', description: 'Merge objects (shallow)' },
    { name: 'Object.freeze', snippet: 'Object.freeze($0)', description: 'Prevent modification of object' },
    { name: 'Object.seal', snippet: 'Object.seal($0)', description: 'Prevent adding/removing properties' },
    { name: 'Object.create', snippet: 'Object.create($0)', description: 'Create object with given prototype' },
    { name: 'Object.fromEntries', snippet: 'Object.fromEntries($0)', description: 'Create object from [key, value] pairs' },
    { name: 'Object.getPrototypeOf', snippet: 'Object.getPrototypeOf($0)', description: 'Get prototype of object' },
    { name: 'Object.setPrototypeOf', snippet: 'Object.setPrototypeOf(${1:obj}, $0)', description: 'Set prototype of object' },
    { name: 'Object.defineProperty', snippet: "Object.defineProperty(${1:obj}, '${2:key}', {\n\tvalue: $0,\n\twritable: true,\n\tenumerable: true,\n\tconfigurable: true\n})", description: 'Define property with descriptor' },
    { name: 'Object.getOwnPropertyNames', snippet: 'Object.getOwnPropertyNames($0)', description: 'Get all own property names including non-enumerable' },
    { name: 'Object.getOwnPropertyDescriptor', snippet: "Object.getOwnPropertyDescriptor(${1:obj}, '${2:key}')", description: 'Get property descriptor' },
    { name: 'Array.from', snippet: 'Array.from($0)', description: 'Create array from iterable or array-like' },
    { name: 'Array.isArray', snippet: 'Array.isArray($0)', description: 'Check if value is an array' },
    { name: 'Array.of', snippet: 'Array.of($0)', description: 'Create array from arguments' },
];

// ── Array methods ──────────────────────────────────────────────────────────────

export const ARRAY_METHODS = [
    { name: 'push', snippet: 'push($0)', description: 'Add elements to end, returns new length' },
    { name: 'pop', snippet: 'pop()', description: 'Remove and return last element' },
    { name: 'shift', snippet: 'shift()', description: 'Remove and return first element' },
    { name: 'unshift', snippet: 'unshift($0)', description: 'Add elements to start, returns new length' },
    { name: 'splice', snippet: 'splice(${1:index}, ${2:deleteCount}, $0)', description: 'Add/remove elements at index' },
    { name: 'slice', snippet: 'slice(${1:start}, ${2:end})', description: 'Return shallow copy of portion' },
    { name: 'concat', snippet: 'concat($0)', description: 'Merge arrays into new array' },
    { name: 'join', snippet: "join('${1:,}')", description: 'Join all elements into a string' },
    { name: 'reverse', snippet: 'reverse()', description: 'Reverse array in place' },
    { name: 'sort', snippet: 'sort((${1:a}, ${2:b}) => $0)', description: 'Sort array in place' },
    { name: 'indexOf', snippet: 'indexOf($0)', description: 'First index of element (-1 if not found)' },
    { name: 'lastIndexOf', snippet: 'lastIndexOf($0)', description: 'Last index of element' },
    { name: 'includes', snippet: 'includes($0)', description: 'Check if array contains value' },
    { name: 'find', snippet: 'find((${1:item}) => $0)', description: 'First element passing test' },
    { name: 'findIndex', snippet: 'findIndex((${1:item}) => $0)', description: 'Index of first element passing test' },
    { name: 'findLast', snippet: 'findLast((${1:item}) => $0)', description: 'Last element passing test' },
    { name: 'findLastIndex', snippet: 'findLastIndex((${1:item}) => $0)', description: 'Index of last element passing test' },
    { name: 'filter', snippet: 'filter((${1:item}) => $0)', description: 'New array with elements passing test' },
    { name: 'map', snippet: 'map((${1:item}) => $0)', description: 'New array with transformed elements' },
    { name: 'reduce', snippet: 'reduce((${1:acc}, ${2:item}) => $0, ${3:initial})', description: 'Reduce to single value (left to right)' },
    { name: 'reduceRight', snippet: 'reduceRight((${1:acc}, ${2:item}) => $0, ${3:initial})', description: 'Reduce to single value (right to left)' },
    { name: 'forEach', snippet: 'forEach((${1:item}, ${2:index}) => {\n\t$0\n})', description: 'Execute function for each element' },
    { name: 'some', snippet: 'some((${1:item}) => $0)', description: 'True if any element passes test' },
    { name: 'every', snippet: 'every((${1:item}) => $0)', description: 'True if all elements pass test' },
    { name: 'flat', snippet: 'flat(${1:1})', description: 'Flatten nested arrays by depth' },
    { name: 'flatMap', snippet: 'flatMap((${1:item}) => $0)', description: 'Map then flatten one level' },
    { name: 'fill', snippet: 'fill(${1:value}, ${2:start}, ${3:end})', description: 'Fill range with static value' },
    { name: 'copyWithin', snippet: 'copyWithin(${1:target}, ${2:start})', description: 'Copy part of array to another position' },
    { name: 'entries', snippet: 'entries()', description: 'Iterator of [index, value] pairs' },
    { name: 'keys', snippet: 'keys()', description: 'Iterator of array indices' },
    { name: 'values', snippet: 'values()', description: 'Iterator of array values' },
    { name: 'at', snippet: 'at(${1:-1})', description: 'Element at index (supports negative)' },
    { name: 'with', snippet: 'with(${1:index}, ${2:value})', description: 'Return new array with element replaced' },
    { name: 'toReversed', snippet: 'toReversed()', description: 'Return new reversed array (non-mutating)' },
    { name: 'toSorted', snippet: 'toSorted((${1:a}, ${2:b}) => $0)', description: 'Return new sorted array (non-mutating)' },
    { name: 'toSpliced', snippet: 'toSpliced(${1:index}, ${2:deleteCount}, $0)', description: 'Return new array with splice (non-mutating)' },
    { name: 'Array.from', snippet: 'Array.from($0)', description: 'Create array from iterable' },
    { name: 'Array.isArray', snippet: 'Array.isArray($0)', description: 'Check if value is array' },
    { name: 'length', snippet: 'length', description: 'Array length' },
];

// ── String methods ─────────────────────────────────────────────────────────────

export const STRING_METHODS = [
    { name: 'length', snippet: 'length', description: 'String length' },
    { name: 'toUpperCase', snippet: 'toUpperCase()', description: 'Convert to uppercase' },
    { name: 'toLowerCase', snippet: 'toLowerCase()', description: 'Convert to lowercase' },
    { name: 'trim', snippet: 'trim()', description: 'Remove whitespace from both ends' },
    { name: 'trimStart', snippet: 'trimStart()', description: 'Remove leading whitespace' },
    { name: 'trimEnd', snippet: 'trimEnd()', description: 'Remove trailing whitespace' },
    { name: 'split', snippet: "split('${1:,}')", description: 'Split into array by separator' },
    { name: 'replace', snippet: "replace('${1:search}', '${2:replacement}')", description: 'Replace first match' },
    { name: 'replaceAll', snippet: "replaceAll('${1:search}', '${2:replacement}')", description: 'Replace all occurrences' },
    { name: 'includes', snippet: "includes('$0')", description: 'Check if string contains substring' },
    { name: 'startsWith', snippet: "startsWith('$0')", description: 'Check if starts with value' },
    { name: 'endsWith', snippet: "endsWith('$0')", description: 'Check if ends with value' },
    { name: 'indexOf', snippet: "indexOf('$0')", description: 'First index of substring (-1 if not found)' },
    { name: 'lastIndexOf', snippet: "lastIndexOf('$0')", description: 'Last index of substring' },
    { name: 'slice', snippet: 'slice(${1:start}, ${2:end})', description: 'Extract part of string (negative indices ok)' },
    { name: 'substring', snippet: 'substring(${1:start}, ${2:end})', description: 'Extract substring between indices' },
    { name: 'substr', snippet: 'substr(${1:start}, ${2:length})', description: 'Extract N chars from start (deprecated)' },
    { name: 'charAt', snippet: 'charAt(${1:index})', description: 'Character at index' },
    { name: 'charCodeAt', snippet: 'charCodeAt(${1:index})', description: 'UTF-16 code unit at index' },
    { name: 'codePointAt', snippet: 'codePointAt(${1:index})', description: 'Unicode code point at index' },
    { name: 'at', snippet: 'at(${1:-1})', description: 'Character at index (supports negative)' },
    { name: 'padStart', snippet: "padStart(${1:length}, '${2: }')", description: 'Pad start to target length' },
    { name: 'padEnd', snippet: "padEnd(${1:length}, '${2: }')", description: 'Pad end to target length' },
    { name: 'repeat', snippet: 'repeat(${1:count})', description: 'Repeat string N times' },
    { name: 'match', snippet: 'match(/$0/)', description: 'Match against regex, returns array or null' },
    { name: 'matchAll', snippet: 'matchAll(/$0/g)', description: 'Iterator of all regex matches' },
    { name: 'search', snippet: 'search(/$0/)', description: 'Index of regex match (-1 if not found)' },
    { name: 'concat', snippet: "concat('$0')", description: 'Concatenate strings' },
    { name: 'normalize', snippet: "normalize('${1:NFC}')", description: 'Unicode normalization form' },
    { name: 'localeCompare', snippet: "localeCompare('$0')", description: 'Locale-aware string comparison' },
    { name: 'toLocaleLowerCase', snippet: 'toLocaleLowerCase()', description: 'Locale-aware lowercase' },
    { name: 'toLocaleUpperCase', snippet: 'toLocaleUpperCase()', description: 'Locale-aware uppercase' },
    { name: 'String.fromCharCode', snippet: 'String.fromCharCode($0)', description: 'Create string from UTF-16 codes' },
    { name: 'String.fromCodePoint', snippet: 'String.fromCodePoint($0)', description: 'Create string from Unicode code points' },
    { name: 'String.raw', snippet: 'String.raw`$0`', description: 'Raw template string (no escape processing)' },
];

// ── Object methods ─────────────────────────────────────────────────────────────

export const OBJECT_METHODS = [
    { name: 'Object.keys', snippet: 'Object.keys($0)', description: 'Get enumerable own keys' },
    { name: 'Object.values', snippet: 'Object.values($0)', description: 'Get enumerable own values' },
    { name: 'Object.entries', snippet: 'Object.entries($0)', description: 'Get [key, value] pairs' },
    { name: 'Object.assign', snippet: 'Object.assign(${1:{}}, $0)', description: 'Merge objects (shallow copy)' },
    { name: 'Object.freeze', snippet: 'Object.freeze($0)', description: 'Make object immutable' },
    { name: 'Object.seal', snippet: 'Object.seal($0)', description: 'Prevent new properties (values still writable)' },
    { name: 'Object.isFrozen', snippet: 'Object.isFrozen($0)', description: 'Check if frozen' },
    { name: 'Object.isSealed', snippet: 'Object.isSealed($0)', description: 'Check if sealed' },
    { name: 'Object.create', snippet: 'Object.create($0)', description: 'Create object with given prototype' },
    { name: 'Object.fromEntries', snippet: 'Object.fromEntries($0)', description: 'Object from [key, value] iterator' },
    { name: 'Object.defineProperty', snippet: "Object.defineProperty(${1:obj}, '${2:key}', {\n\tvalue: $0,\n\twritable: true,\n\tenumerable: true\n})", description: 'Define property descriptor' },
    { name: 'Object.defineProperties', snippet: "Object.defineProperties(${1:obj}, {\n\t'${2:key}': { value: $0, writable: true }\n})", description: 'Define multiple property descriptors' },
    { name: 'Object.getPrototypeOf', snippet: 'Object.getPrototypeOf($0)', description: 'Get prototype chain object' },
    { name: 'Object.setPrototypeOf', snippet: 'Object.setPrototypeOf(${1:obj}, $0)', description: 'Set prototype of object' },
    { name: 'Object.getOwnPropertyNames', snippet: 'Object.getOwnPropertyNames($0)', description: 'All own property names (including non-enumerable)' },
    { name: 'Object.getOwnPropertyDescriptor', snippet: "Object.getOwnPropertyDescriptor(${1:obj}, '${2:key}')", description: 'Get property descriptor' },
    { name: 'Object.getOwnPropertyDescriptors', snippet: 'Object.getOwnPropertyDescriptors($0)', description: 'Get all property descriptors' },
    { name: 'Object.getOwnPropertySymbols', snippet: 'Object.getOwnPropertySymbols($0)', description: 'Get own Symbol keys' },
    { name: 'Object.is', snippet: 'Object.is(${1:value1}, ${2:value2})', description: 'Strict equality (handles NaN and ±0)' },
    { name: 'Object.hasOwn', snippet: "Object.hasOwn(${1:obj}, '${2:key}')", description: 'Check own property (modern replacement for hasOwnProperty)' },
    { name: 'hasOwnProperty', snippet: "hasOwnProperty('$0')", description: 'Check if own property (legacy)' },
];

// ── DOM event names (used with addEventListener) ───────────────────────────────

export const DOM_EVENTS = [
    // Mouse
    { name: 'click', description: 'Left mouse button click' },
    { name: 'dblclick', description: 'Double click' },
    { name: 'mousedown', description: 'Mouse button pressed' },
    { name: 'mouseup', description: 'Mouse button released' },
    { name: 'mouseover', description: 'Mouse enters element (bubbles)' },
    { name: 'mouseout', description: 'Mouse leaves element (bubbles)' },
    { name: 'mouseenter', description: 'Mouse enters element (does not bubble)' },
    { name: 'mouseleave', description: 'Mouse leaves element (does not bubble)' },
    { name: 'mousemove', description: 'Mouse moves over element' },
    { name: 'contextmenu', description: 'Right-click context menu' },
    { name: 'auxclick', description: 'Non-primary button click (e.g. middle click)' },
    // Keyboard
    { name: 'keydown', description: 'Key pressed down' },
    { name: 'keyup', description: 'Key released' },
    { name: 'keypress', description: 'Key pressed and released (deprecated)' },
    // Focus
    { name: 'focus', description: 'Element gains focus (does not bubble)' },
    { name: 'blur', description: 'Element loses focus (does not bubble)' },
    { name: 'focusin', description: 'Element gains focus (bubbles)' },
    { name: 'focusout', description: 'Element loses focus (bubbles)' },
    // Form / Input
    { name: 'change', description: 'Input committed (after blur or selection change)' },
    { name: 'input', description: 'Input value changing in real time' },
    { name: 'beforeinput', description: 'Before value is modified' },
    { name: 'submit', description: 'Form submitted' },
    { name: 'reset', description: 'Form reset' },
    { name: 'invalid', description: 'Form validation failed' },
    { name: 'select', description: 'Text selected in input/textarea' },
    // Page lifecycle
    { name: 'load', description: 'Page or resource fully loaded' },
    { name: 'DOMContentLoaded', description: 'DOM ready, stylesheets and images may still load' },
    { name: 'unload', description: 'Page is unloading' },
    { name: 'beforeunload', description: 'Before page unloads (can prompt confirmation)' },
    { name: 'pagehide', description: 'Page hidden (back/forward navigation)' },
    { name: 'pageshow', description: 'Page shown (including from bfcache)' },
    { name: 'visibilitychange', description: 'Tab visibility changed (Page Visibility API)' },
    { name: 'readystatechange', description: 'document.readyState changed' },
    // Window
    { name: 'resize', description: 'Window or element resized' },
    { name: 'scroll', description: 'Element or window scrolled' },
    { name: 'scrollend', description: 'Scrolling stopped' },
    { name: 'hashchange', description: 'URL hash fragment changed' },
    { name: 'popstate', description: 'History navigation (back/forward)' },
    { name: 'message', description: 'Message received (postMessage / Worker / WebSocket)' },
    { name: 'messageerror', description: 'Message could not be deserialized' },
    { name: 'online', description: 'Browser went online' },
    { name: 'offline', description: 'Browser went offline' },
    { name: 'storage', description: 'localStorage or sessionStorage changed in another tab' },
    { name: 'languagechange', description: 'Browser language preference changed' },
    // Media
    { name: 'play', description: 'Media playback started' },
    { name: 'pause', description: 'Media playback paused' },
    { name: 'ended', description: 'Media playback ended' },
    { name: 'timeupdate', description: 'Media playback position changed' },
    { name: 'volumechange', description: 'Media volume or muted state changed' },
    { name: 'seeking', description: 'Media seek started' },
    { name: 'seeked', description: 'Media seek completed' },
    { name: 'canplay', description: 'Media can start playing' },
    { name: 'canplaythrough', description: 'Media can play to end without buffering' },
    { name: 'waiting', description: 'Media is waiting to buffer' },
    { name: 'stalled', description: 'Browser trying to fetch but data not coming' },
    { name: 'loadeddata', description: 'Current frame loaded' },
    { name: 'loadedmetadata', description: 'Media metadata (duration, dimensions) loaded' },
    { name: 'durationchange', description: 'Duration attribute changed' },
    { name: 'ratechange', description: 'Playback speed changed' },
    // Drag and Drop
    { name: 'drag', description: 'Draggable element being dragged' },
    { name: 'dragstart', description: 'Drag operation started' },
    { name: 'dragend', description: 'Drag operation ended' },
    { name: 'dragenter', description: 'Dragged item entered drop target' },
    { name: 'dragleave', description: 'Dragged item left drop target' },
    { name: 'dragover', description: 'Dragged item over drop target (must prevent default to allow drop)' },
    { name: 'drop', description: 'Item dropped on drop target' },
    // Touch
    { name: 'touchstart', description: 'Touch contact placed on surface' },
    { name: 'touchend', description: 'Touch contact removed' },
    { name: 'touchmove', description: 'Touch contact moved' },
    { name: 'touchcancel', description: 'Touch interrupted (e.g. incoming call)' },
    // Pointer (unified mouse/touch/stylus)
    { name: 'pointerdown', description: 'Pointer pressed (mouse/touch/pen)' },
    { name: 'pointerup', description: 'Pointer released' },
    { name: 'pointermove', description: 'Pointer moved' },
    { name: 'pointerover', description: 'Pointer entered element (bubbles)' },
    { name: 'pointerout', description: 'Pointer left element (bubbles)' },
    { name: 'pointerenter', description: 'Pointer entered element (no bubble)' },
    { name: 'pointerleave', description: 'Pointer left element (no bubble)' },
    { name: 'pointercancel', description: 'Pointer event cancelled' },
    { name: 'gotpointercapture', description: 'Element captured pointer' },
    { name: 'lostpointercapture', description: 'Element lost pointer capture' },
    // Wheel / Scroll
    { name: 'wheel', description: 'Mouse wheel or touchpad scroll' },
    // CSS Animations & Transitions
    { name: 'animationstart', description: 'CSS animation started' },
    { name: 'animationend', description: 'CSS animation completed' },
    { name: 'animationiteration', description: 'CSS animation iteration completed' },
    { name: 'animationcancel', description: 'CSS animation aborted' },
    { name: 'transitionstart', description: 'CSS transition started' },
    { name: 'transitionend', description: 'CSS transition completed' },
    { name: 'transitionrun', description: 'CSS transition created (includes delay)' },
    { name: 'transitioncancel', description: 'CSS transition aborted' },
    // Clipboard
    { name: 'copy', description: 'Content copied to clipboard' },
    { name: 'cut', description: 'Content cut to clipboard' },
    { name: 'paste', description: 'Content pasted from clipboard' },
    // Error / Network
    { name: 'error', description: 'Error loading resource or runtime error' },
    { name: 'abort', description: 'Resource loading aborted' },
    { name: 'loadstart', description: 'Resource loading started' },
    { name: 'progress', description: 'Resource loading progress (XHR, fetch)' },
    { name: 'loadend', description: 'Resource loading completed (success or fail)' },
    // Fullscreen / Pointer lock
    { name: 'fullscreenchange', description: 'Element entered or exited fullscreen' },
    { name: 'fullscreenerror', description: 'Failed to enter fullscreen' },
    // Selection
    { name: 'selectionchange', description: 'Text selection changed in document' },
    { name: 'selectstart', description: 'Text selection started' },
    // Custom
    { name: 'toggle', description: 'Details/summary element opened or closed' },
    { name: 'close', description: 'Dialog element closed' },
    { name: 'cancel', description: 'Dialog element cancelled (Escape key)' },
    { name: 'open', description: 'WebSocket or EventSource connected' },
];