/**
 * jsGlobals.ts
 * JavaScript global functions, objects, and DOM APIs.
 * Split into logical groups — globals, DOM, events, arrays, objects, etc.
 */

// ── Top-level global objects (suggested when typing standalone) ────────────────

export const JS_GLOBAL_OBJECTS = [
    { name: 'document', snippet: 'document', description: 'The HTML document object' },
    { name: 'window', snippet: 'window', description: 'The browser window object' },
    { name: 'console', snippet: 'console', description: 'Browser console object' },
    { name: 'Math', snippet: 'Math', description: 'Math utility object' },
    { name: 'JSON', snippet: 'JSON', description: 'JSON parse/stringify object' },
    { name: 'Date', snippet: 'Date', description: 'Date and time object' },
    { name: 'Array', snippet: 'Array', description: 'Array utility object' },
    { name: 'Object', snippet: 'Object', description: 'Object utility' },
    { name: 'String', snippet: 'String', description: 'String utility' },
    { name: 'Number', snippet: 'Number', description: 'Number utility' },
    { name: 'Boolean', snippet: 'Boolean', description: 'Boolean utility' },
    { name: 'Promise', snippet: 'Promise', description: 'Promise object' },
    { name: 'Error', snippet: 'Error', description: 'Error object' },
    { name: 'RegExp', snippet: 'RegExp', description: 'Regular expression object' },
    { name: 'Map', snippet: 'Map', description: 'Map collection' },
    { name: 'Set', snippet: 'Set', description: 'Set collection' },
    { name: 'localStorage', snippet: 'localStorage', description: 'Local storage object' },
    { name: 'sessionStorage', snippet: 'sessionStorage', description: 'Session storage object' },
    { name: 'location', snippet: 'location', description: 'Window location object' },
    { name: 'history', snippet: 'history', description: 'Browser history object' },
    { name: 'navigator', snippet: 'navigator', description: 'Browser navigator object' },
    { name: 'screen', snippet: 'screen', description: 'Screen information object' },
    { name: 'event', snippet: 'event', description: 'Current event object' },
    { name: 'undefined', snippet: 'undefined', description: 'Undefined value' },
    { name: 'null', snippet: 'null', description: 'Null value' },
    { name: 'true', snippet: 'true', description: 'Boolean true' },
    { name: 'false', snippet: 'false', description: 'Boolean false' },
    { name: 'Infinity', snippet: 'Infinity', description: 'Infinity value' },
    { name: 'NaN', snippet: 'NaN', description: 'Not a number value' },
    { name: 'this', snippet: 'this', description: 'Current context object' },
    { name: 'arguments', snippet: 'arguments', description: 'Function arguments object' },
    { name: 'globalThis', snippet: 'globalThis', description: 'Global this object' },
];

// ── Console ────────────────────────────────────────────────────────────────────

export const CONSOLE_METHODS = [
    { name: 'log', snippet: 'log($0)', description: 'Log to console' },
    { name: 'error', snippet: 'error($0)', description: 'Log error to console' },
    { name: 'warn', snippet: 'warn($0)', description: 'Log warning to console' },
    { name: 'info', snippet: 'info($0)', description: 'Log info to console' },
    { name: 'table', snippet: 'table($0)', description: 'Log data as table' },
    { name: 'dir', snippet: 'dir($0)', description: 'Log object properties' },
    { name: 'group', snippet: "group('$0')", description: 'Start console group' },
    { name: 'groupEnd', snippet: 'groupEnd()', description: 'End console group' },
    { name: 'time', snippet: "time('$0')", description: 'Start timer' },
    { name: 'timeEnd', snippet: "timeEnd('$0')", description: 'End timer' },
    { name: 'clear', snippet: 'clear()', description: 'Clear console' },
    { name: 'count', snippet: "count('$0')", description: 'Count calls' },
    { name: 'assert', snippet: "assert(${1:condition}, '$0')", description: 'Assert condition' },
];

// ── Document methods ───────────────────────────────────────────────────────────

export const DOCUMENT_METHODS = [
    { name: 'getElementById', snippet: "getElementById('$0')", description: 'Get element by ID' },
    { name: 'getElementsByClassName', snippet: "getElementsByClassName('$0')", description: 'Get elements by class name' },
    { name: 'getElementsByTagName', snippet: "getElementsByTagName('$0')", description: 'Get elements by tag name' },
    { name: 'querySelector', snippet: "querySelector('$0')", description: 'Get first matching element' },
    { name: 'querySelectorAll', snippet: "querySelectorAll('$0')", description: 'Get all matching elements' },
    { name: 'createElement', snippet: "createElement('$0')", description: 'Create a new element' },
    { name: 'createTextNode', snippet: "createTextNode('$0')", description: 'Create a text node' },
    { name: 'createDocumentFragment', snippet: 'createDocumentFragment()', description: 'Create a document fragment' },
    { name: 'addEventListener', snippet: "addEventListener('${1:DOMContentLoaded}', () => {\n\t$0\n})", description: 'Add event listener to document' },
    { name: 'removeEventListener', snippet: "removeEventListener('${1:event}', ${2:handler})", description: 'Remove event listener' },
    { name: 'write', snippet: "write('$0')", description: 'Write to document' },
    { name: 'writeln', snippet: "writeln('$0')", description: 'Write line to document' },
    { name: 'open', snippet: 'open()', description: 'Open document stream' },
    { name: 'close', snippet: 'close()', description: 'Close document stream' },
    { name: 'cookie', snippet: 'cookie', description: 'Document cookies' },
    { name: 'title', snippet: 'title', description: 'Document title' },
    { name: 'URL', snippet: 'URL', description: 'Document URL' },
    { name: 'domain', snippet: 'domain', description: 'Document domain' },
    { name: 'referrer', snippet: 'referrer', description: 'Referring document URL' },
    { name: 'body', snippet: 'body', description: 'Document body element' },
    { name: 'head', snippet: 'head', description: 'Document head element' },
    { name: 'forms', snippet: 'forms', description: 'All form elements' },
    { name: 'images', snippet: 'images', description: 'All image elements' },
    { name: 'links', snippet: 'links', description: 'All link elements' },
    { name: 'readyState', snippet: 'readyState', description: 'Document loading state' },
    { name: 'documentElement', snippet: 'documentElement', description: 'Root html element' },
    { name: 'activeElement', snippet: 'activeElement', description: 'Currently focused element' },
];

// ── Element methods (used after querySelector etc.) ────────────────────────────

export const ELEMENT_METHODS = [
    { name: 'addEventListener', snippet: "addEventListener('${1:click}', ($2) => {\n\t$0\n})", description: 'Add event listener' },
    { name: 'removeEventListener', snippet: "removeEventListener('${1:click}', ${2:handler})", description: 'Remove event listener' },
    { name: 'appendChild', snippet: 'appendChild($0)', description: 'Append child element' },
    { name: 'removeChild', snippet: 'removeChild($0)', description: 'Remove child element' },
    { name: 'insertBefore', snippet: 'insertBefore(${1:newNode}, ${2:referenceNode})', description: 'Insert before node' },
    { name: 'replaceChild', snippet: 'replaceChild(${1:newNode}, ${2:oldNode})', description: 'Replace child node' },
    { name: 'cloneNode', snippet: 'cloneNode(${1:true})', description: 'Clone node' },
    { name: 'contains', snippet: 'contains($0)', description: 'Check if contains node' },
    { name: 'getAttribute', snippet: "getAttribute('$0')", description: 'Get attribute value' },
    { name: 'setAttribute', snippet: "setAttribute('${1:name}', '${2:value}')", description: 'Set attribute value' },
    { name: 'removeAttribute', snippet: "removeAttribute('$0')", description: 'Remove attribute' },
    { name: 'hasAttribute', snippet: "hasAttribute('$0')", description: 'Check if attribute exists' },
    { name: 'classList', snippet: 'classList', description: 'Element class list' },
    { name: 'style', snippet: 'style', description: 'Element inline styles' },
    { name: 'innerHTML', snippet: "innerHTML = '$0'", description: 'Set inner HTML' },
    { name: 'outerHTML', snippet: 'outerHTML', description: 'Get outer HTML' },
    { name: 'textContent', snippet: "textContent = '$0'", description: 'Set text content' },
    { name: 'innerText', snippet: "innerText = '$0'", description: 'Set inner text' },
    { name: 'value', snippet: 'value', description: 'Element value (inputs)' },
    { name: 'checked', snippet: 'checked', description: 'Checkbox checked state' },
    { name: 'disabled', snippet: 'disabled', description: 'Element disabled state' },
    { name: 'focus', snippet: 'focus()', description: 'Focus element' },
    { name: 'blur', snippet: 'blur()', description: 'Blur element' },
    { name: 'click', snippet: 'click()', description: 'Simulate click' },
    { name: 'submit', snippet: 'submit()', description: 'Submit form' },
    { name: 'reset', snippet: 'reset()', description: 'Reset form' },
    { name: 'scrollIntoView', snippet: 'scrollIntoView(${1:true})', description: 'Scroll element into view' },
    { name: 'getBoundingClientRect', snippet: 'getBoundingClientRect()', description: 'Get element bounding box' },
    { name: 'closest', snippet: "closest('$0')", description: 'Find closest ancestor matching selector' },
    { name: 'matches', snippet: "matches('$0')", description: 'Check if element matches selector' },
    { name: 'querySelector', snippet: "querySelector('$0')", description: 'Find child element' },
    { name: 'querySelectorAll', snippet: "querySelectorAll('$0')", description: 'Find all child elements' },
    { name: 'parentElement', snippet: 'parentElement', description: 'Parent element' },
    { name: 'children', snippet: 'children', description: 'Child elements' },
    { name: 'firstElementChild', snippet: 'firstElementChild', description: 'First child element' },
    { name: 'lastElementChild', snippet: 'lastElementChild', description: 'Last child element' },
    { name: 'nextElementSibling', snippet: 'nextElementSibling', description: 'Next sibling element' },
    { name: 'previousElementSibling', snippet: 'previousElementSibling', description: 'Previous sibling element' },
    { name: 'id', snippet: 'id', description: 'Element ID' },
    { name: 'className', snippet: 'className', description: 'Element class name string' },
    { name: 'tagName', snippet: 'tagName', description: 'Element tag name' },
    { name: 'dataset', snippet: 'dataset.${0:key}', description: 'Access data attributes' },
];

// ── Window methods ─────────────────────────────────────────────────────────────

export const WINDOW_METHODS = [
    { name: 'alert', snippet: "alert('$0')", description: 'Show alert dialog' },
    { name: 'confirm', snippet: "confirm('$0')", description: 'Show confirm dialog' },
    { name: 'prompt', snippet: "prompt('$0')", description: 'Show prompt dialog' },
    { name: 'setTimeout', snippet: 'setTimeout(() => {\n\t$0\n}, ${1:1000})', description: 'Execute after delay' },
    { name: 'setInterval', snippet: 'setInterval(() => {\n\t$0\n}, ${1:1000})', description: 'Execute repeatedly' },
    { name: 'clearTimeout', snippet: 'clearTimeout($0)', description: 'Cancel setTimeout' },
    { name: 'clearInterval', snippet: 'clearInterval($0)', description: 'Cancel setInterval' },
    { name: 'requestAnimationFrame', snippet: 'requestAnimationFrame(($0) => {\n\t\n})', description: 'Request animation frame' },
    { name: 'cancelAnimationFrame', snippet: 'cancelAnimationFrame($0)', description: 'Cancel animation frame' },
    { name: 'open', snippet: "open('${1:url}', '${2:_blank}')", description: 'Open new window/tab' },
    { name: 'close', snippet: 'close()', description: 'Close window' },
    { name: 'focus', snippet: 'focus()', description: 'Focus window' },
    { name: 'blur', snippet: 'blur()', description: 'Blur window' },
    { name: 'scrollTo', snippet: 'scrollTo(${1:0}, ${2:0})', description: 'Scroll to position' },
    { name: 'scrollBy', snippet: 'scrollBy(${1:0}, ${2:100})', description: 'Scroll by amount' },
    { name: 'print', snippet: 'print()', description: 'Print page' },
    { name: 'innerWidth', snippet: 'innerWidth', description: 'Window inner width' },
    { name: 'innerHeight', snippet: 'innerHeight', description: 'Window inner height' },
    { name: 'pageXOffset', snippet: 'pageXOffset', description: 'Horizontal scroll position' },
    { name: 'pageYOffset', snippet: 'pageYOffset', description: 'Vertical scroll position' },
];

// ── Global functions ───────────────────────────────────────────────────────────

export const JS_GLOBAL_FUNCTIONS = [
    { name: 'parseInt', snippet: 'parseInt($0)', description: 'Parse to integer' },
    { name: 'parseFloat', snippet: 'parseFloat($0)', description: 'Parse to float' },
    { name: 'isNaN', snippet: 'isNaN($0)', description: 'Check if NaN' },
    { name: 'isFinite', snippet: 'isFinite($0)', description: 'Check if finite number' },
    { name: 'Number', snippet: 'Number($0)', description: 'Convert to number' },
    { name: 'String', snippet: 'String($0)', description: 'Convert to string' },
    { name: 'Boolean', snippet: 'Boolean($0)', description: 'Convert to boolean' },
    { name: 'JSON.parse', snippet: 'JSON.parse($0)', description: 'Parse JSON string' },
    { name: 'JSON.stringify', snippet: 'JSON.stringify(${1:obj}, ${2:null}, ${3:2})', description: 'Convert to JSON string' },
    { name: 'Math.round', snippet: 'Math.round($0)', description: 'Round to nearest integer' },
    { name: 'Math.floor', snippet: 'Math.floor($0)', description: 'Round down' },
    { name: 'Math.ceil', snippet: 'Math.ceil($0)', description: 'Round up' },
    { name: 'Math.abs', snippet: 'Math.abs($0)', description: 'Absolute value' },
    { name: 'Math.max', snippet: 'Math.max($0)', description: 'Maximum value' },
    { name: 'Math.min', snippet: 'Math.min($0)', description: 'Minimum value' },
    { name: 'Math.random', snippet: 'Math.random()', description: 'Random number between 0 and 1' },
    { name: 'Math.pow', snippet: 'Math.pow(${1:base}, ${2:exponent})', description: 'Power of a number' },
    { name: 'Math.sqrt', snippet: 'Math.sqrt($0)', description: 'Square root' },
    { name: 'Math.PI', snippet: 'Math.PI', description: 'Pi constant' },
    { name: 'Date.now', snippet: 'Date.now()', description: 'Current timestamp in ms' },
    { name: 'new Date', snippet: 'new Date()', description: 'Create date object' },
    { name: 'encodeURIComponent', snippet: 'encodeURIComponent($0)', description: 'Encode URI component' },
    { name: 'decodeURIComponent', snippet: 'decodeURIComponent($0)', description: 'Decode URI component' },
    { name: 'encodeURI', snippet: 'encodeURI($0)', description: 'Encode URI' },
    { name: 'decodeURI', snippet: 'decodeURI($0)', description: 'Decode URI' },
    { name: 'fetch', snippet: "fetch('$1')\n\t.then(res => res.json())\n\t.then(data => {\n\t\t$0\n\t})\n\t.catch(err => console.error(err))", description: 'Fetch API call' },
    { name: 'fetch async', snippet: "const response = await fetch('$1');\nconst data = await response.json();\n$0", description: 'Fetch with async/await' },
    { name: 'Promise', snippet: 'new Promise((resolve, reject) => {\n\t$0\n})', description: 'Create a promise' },
    { name: 'Promise.all', snippet: 'Promise.all([$0])', description: 'Wait for all promises' },
    { name: 'Promise.resolve', snippet: 'Promise.resolve($0)', description: 'Resolve a promise' },
    { name: 'Promise.reject', snippet: 'Promise.reject($0)', description: 'Reject a promise' },
];

// ── Array methods ──────────────────────────────────────────────────────────────

export const ARRAY_METHODS = [
    { name: 'push', snippet: 'push($0)', description: 'Add to end of array' },
    { name: 'pop', snippet: 'pop()', description: 'Remove from end of array' },
    { name: 'shift', snippet: 'shift()', description: 'Remove from start of array' },
    { name: 'unshift', snippet: 'unshift($0)', description: 'Add to start of array' },
    { name: 'splice', snippet: 'splice(${1:index}, ${2:deleteCount}, $0)', description: 'Add/remove array elements' },
    { name: 'slice', snippet: 'slice(${1:start}, ${2:end})', description: 'Extract part of array' },
    { name: 'concat', snippet: 'concat($0)', description: 'Merge arrays' },
    { name: 'join', snippet: "join('${1:,}')", description: 'Join array into string' },
    { name: 'reverse', snippet: 'reverse()', description: 'Reverse array' },
    { name: 'sort', snippet: 'sort((${1:a}, ${2:b}) => $0)', description: 'Sort array' },
    { name: 'indexOf', snippet: 'indexOf($0)', description: 'Find index of element' },
    { name: 'lastIndexOf', snippet: 'lastIndexOf($0)', description: 'Find last index of element' },
    { name: 'includes', snippet: 'includes($0)', description: 'Check if array includes value' },
    { name: 'find', snippet: 'find((${1:item}) => $0)', description: 'Find first matching element' },
    { name: 'findIndex', snippet: 'findIndex((${1:item}) => $0)', description: 'Find index of first match' },
    { name: 'filter', snippet: 'filter((${1:item}) => $0)', description: 'Filter array elements' },
    { name: 'map', snippet: 'map((${1:item}) => $0)', description: 'Transform array elements' },
    { name: 'reduce', snippet: 'reduce((${1:acc}, ${2:item}) => $0, ${3:initial})', description: 'Reduce array to single value' },
    { name: 'forEach', snippet: 'forEach((${1:item}) => {\n\t$0\n})', description: 'Iterate over array' },
    { name: 'some', snippet: 'some((${1:item}) => $0)', description: 'Check if any element matches' },
    { name: 'every', snippet: 'every((${1:item}) => $0)', description: 'Check if all elements match' },
    { name: 'flat', snippet: 'flat(${1:1})', description: 'Flatten nested array' },
    { name: 'flatMap', snippet: 'flatMap((${1:item}) => $0)', description: 'Map then flatten' },
    { name: 'fill', snippet: 'fill(${1:value}, ${2:start}, ${3:end})', description: 'Fill array with value' },
    { name: 'Array.from', snippet: 'Array.from($0)', description: 'Create array from iterable' },
    { name: 'Array.isArray', snippet: 'Array.isArray($0)', description: 'Check if value is array' },
    { name: 'length', snippet: 'length', description: 'Array length' },
];

// ── String methods ─────────────────────────────────────────────────────────────

export const STRING_METHODS = [
    { name: 'length', snippet: 'length', description: 'String length' },
    { name: 'toUpperCase', snippet: 'toUpperCase()', description: 'Convert to uppercase' },
    { name: 'toLowerCase', snippet: 'toLowerCase()', description: 'Convert to lowercase' },
    { name: 'trim', snippet: 'trim()', description: 'Remove whitespace from both ends' },
    { name: 'trimStart', snippet: 'trimStart()', description: 'Remove leading whitespace' },
    { name: 'trimEnd', snippet: 'trimEnd()', description: 'Remove trailing whitespace' },
    { name: 'split', snippet: "split('${1:,}')", description: 'Split into array' },
    { name: 'replace', snippet: "replace('${1:search}', '${2:replacement}')", description: 'Replace first match' },
    { name: 'replaceAll', snippet: "replaceAll('${1:search}', '${2:replacement}')", description: 'Replace all matches' },
    { name: 'includes', snippet: "includes('$0')", description: 'Check if string contains value' },
    { name: 'startsWith', snippet: "startsWith('$0')", description: 'Check if starts with value' },
    { name: 'endsWith', snippet: "endsWith('$0')", description: 'Check if ends with value' },
    { name: 'indexOf', snippet: "indexOf('$0')", description: 'Find index of substring' },
    { name: 'lastIndexOf', snippet: "lastIndexOf('$0')", description: 'Find last index of substring' },
    { name: 'slice', snippet: 'slice(${1:start}, ${2:end})', description: 'Extract part of string' },
    { name: 'substring', snippet: 'substring(${1:start}, ${2:end})', description: 'Extract substring' },
    { name: 'charAt', snippet: 'charAt(${1:index})', description: 'Get character at index' },
    { name: 'charCodeAt', snippet: 'charCodeAt(${1:index})', description: 'Get char code at index' },
    { name: 'padStart', snippet: "padStart(${1:length}, '${2: }')", description: 'Pad start of string' },
    { name: 'padEnd', snippet: "padEnd(${1:length}, '${2: }')", description: 'Pad end of string' },
    { name: 'repeat', snippet: 'repeat(${1:count})', description: 'Repeat string' },
    { name: 'match', snippet: 'match(/$0/)', description: 'Match against regex' },
    { name: 'matchAll', snippet: 'matchAll(/$0/g)', description: 'Match all against regex' },
    { name: 'search', snippet: 'search(/$0/)', description: 'Search with regex' },
    { name: 'concat', snippet: "concat('$0')", description: 'Concatenate strings' },
    { name: 'at', snippet: 'at(${1:-1})', description: 'Get character at index (supports negative)' },
    { name: 'String.fromCharCode', snippet: 'String.fromCharCode($0)', description: 'Create string from char codes' },
];

// ── Object methods ─────────────────────────────────────────────────────────────

export const OBJECT_METHODS = [
    { name: 'Object.keys', snippet: 'Object.keys($0)', description: 'Get object keys' },
    { name: 'Object.values', snippet: 'Object.values($0)', description: 'Get object values' },
    { name: 'Object.entries', snippet: 'Object.entries($0)', description: 'Get key-value pairs' },
    { name: 'Object.assign', snippet: 'Object.assign(${1:{}}, $0)', description: 'Merge objects' },
    { name: 'Object.freeze', snippet: 'Object.freeze($0)', description: 'Freeze object' },
    { name: 'Object.create', snippet: 'Object.create($0)', description: 'Create object with prototype' },
    { name: 'Object.defineProperty', snippet: "Object.defineProperty(${1:obj}, '${2:key}', {\n\tvalue: $0,\n\twritable: true,\n\tenumerable: true\n})", description: 'Define object property' },
    { name: 'hasOwnProperty', snippet: "hasOwnProperty('$0')", description: 'Check own property' },
];

// ── DOM event names (used with addEventListener) ───────────────────────────────

export const DOM_EVENTS = [
    { name: 'click', description: 'Mouse click' },
    { name: 'dblclick', description: 'Mouse double click' },
    { name: 'mousedown', description: 'Mouse button pressed' },
    { name: 'mouseup', description: 'Mouse button released' },
    { name: 'mouseover', description: 'Mouse enters element' },
    { name: 'mouseout', description: 'Mouse leaves element' },
    { name: 'mousemove', description: 'Mouse moves over element' },
    { name: 'keydown', description: 'Key pressed down' },
    { name: 'keyup', description: 'Key released' },
    { name: 'keypress', description: 'Key pressed' },
    { name: 'focus', description: 'Element gains focus' },
    { name: 'blur', description: 'Element loses focus' },
    { name: 'change', description: 'Input value changed' },
    { name: 'input', description: 'Input value changing' },
    { name: 'submit', description: 'Form submitted' },
    { name: 'reset', description: 'Form reset' },
    { name: 'load', description: 'Page or image loaded' },
    { name: 'unload', description: 'Page unloaded' },
    { name: 'DOMContentLoaded', description: 'DOM ready, before images' },
    { name: 'resize', description: 'Window resized' },
    { name: 'scroll', description: 'Element scrolled' },
    { name: 'contextmenu', description: 'Right click context menu' },
    { name: 'drag', description: 'Element being dragged' },
    { name: 'dragstart', description: 'Drag started' },
    { name: 'dragend', description: 'Drag ended' },
    { name: 'dragover', description: 'Dragged over element' },
    { name: 'drop', description: 'Element dropped' },
    { name: 'touchstart', description: 'Touch started' },
    { name: 'touchend', description: 'Touch ended' },
    { name: 'touchmove', description: 'Touch moved' },
    { name: 'animationstart', description: 'CSS animation started' },
    { name: 'animationend', description: 'CSS animation ended' },
    { name: 'transitionend', description: 'CSS transition ended' },
    { name: 'error', description: 'Error occurred' },
    { name: 'abort', description: 'Loading aborted' },
    { name: 'beforeunload', description: 'Before page unloads' },
    { name: 'hashchange', description: 'URL hash changed' },
    { name: 'popstate', description: 'History state changed' },
    { name: 'storage', description: 'localStorage/sessionStorage changed' },
    { name: 'online', description: 'Browser went online' },
    { name: 'offline', description: 'Browser went offline' },
    { name: 'copy', description: 'Content copied' },
    { name: 'cut', description: 'Content cut' },
    { name: 'paste', description: 'Content pasted' },
    { name: 'wheel', description: 'Scroll wheel moved' },
    { name: 'pointerdown', description: 'Pointer pressed' },
    { name: 'pointerup', description: 'Pointer released' },
    { name: 'pointermove', description: 'Pointer moved' },
];